load("@build_bazel_rules_swift//swift:swift_test.bzl", "swift_test")

swift_test(
    name = "WasmClientLiveTests",
    srcs = [
        "AIArtProviderFailoverTests.swift",
        "ChatStreamTests.swift",
    ],
    module_name = "WasmClientLiveTests",
    deps = [
        "//Sources/WasmClient",
        "//Sources/WasmClientLive",
        "@swiftpkg_swift_dependencies//:Dependencies",
    ],
)
