// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: aiart.proto
//
// AiartService/ListModels response message. Split into its own file because
// the checked-in `aiart.pb.swift` predates the `ListModels` rpc (it only had
// the metadata-driven `model_infos` lookup). `TypesModelInfo` and `AiartMode`
// are provided by the FlowKit binary + the existing `aiart.pb.swift`, so only
// the response wrapper is emitted here. Kept byte-for-byte identical to
// flow-kit-example's generated `AiartListModelsResponse` so the FlowKit
// `run(method:)` decode contract matches the plugin.

import SwiftProtobuf

#if canImport(FlowKit)
    import FlowKit
#else
    import WasmSwiftProtobuf
#endif

private let _protobuf_package = "asyncify.aiart"

public struct AiartListModelsResponse: Sendable {
    public var models: [TypesModelInfo] = []

    public var defaultModelID: String {
        get { _defaultModelID ?? String() }
        set { _defaultModelID = newValue }
    }
    /// Returns true if `defaultModelID` has been explicitly set.
    public var hasDefaultModelID: Bool { self._defaultModelID != nil }
    /// Clears the value of `defaultModelID`. Subsequent reads from it will return its default value.
    public mutating func clearDefaultModelID() { self._defaultModelID = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _defaultModelID: String? = nil
}

extension AiartListModelsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding
{
    public static let protoMessageName: String = _protobuf_package + ".ListModelsResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(
        bytecode: "\0\u{1}models\0\u{1}default_model_id\0")

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try { try decoder.decodeRepeatedMessageField(value: &self.models) }()
            case 2: try { try decoder.decodeSingularStringField(value: &self._defaultModelID) }()
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !self.models.isEmpty {
            try visitor.visitRepeatedMessageField(value: self.models, fieldNumber: 1)
        }
        try {
            if let v = self._defaultModelID {
                try visitor.visitSingularStringField(value: v, fieldNumber: 2)
            }
        }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: AiartListModelsResponse, rhs: AiartListModelsResponse) -> Bool {
        if lhs.models != rhs.models { return false }
        if lhs._defaultModelID != rhs._defaultModelID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
