// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: aiart.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf
#if canImport(FlowKit)
import FlowKit
#else
import WasmSwiftProtobuf
#endif

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum AiartStyle: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case anime // = 1
  case cyberpunk // = 2
  case watercolor // = 3
  case pixelArt // = 4
  case threeDCartoon // = 5
  case fantasy // = 6
  case oilPainting // = 7
  case lineArt // = 8
  case minimal // = 9
  case photoreal // = 10
  case postage // = 11
  case vintagePostage // = 12
  case waxSeal // = 13
  case rubberStamp // = 14
  case engraved // = 15
  case botanicalPostage // = 16
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .anime
    case 2: self = .cyberpunk
    case 3: self = .watercolor
    case 4: self = .pixelArt
    case 5: self = .threeDCartoon
    case 6: self = .fantasy
    case 7: self = .oilPainting
    case 8: self = .lineArt
    case 9: self = .minimal
    case 10: self = .photoreal
    case 11: self = .postage
    case 12: self = .vintagePostage
    case 13: self = .waxSeal
    case 14: self = .rubberStamp
    case 15: self = .engraved
    case 16: self = .botanicalPostage
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .anime: return 1
    case .cyberpunk: return 2
    case .watercolor: return 3
    case .pixelArt: return 4
    case .threeDCartoon: return 5
    case .fantasy: return 6
    case .oilPainting: return 7
    case .lineArt: return 8
    case .minimal: return 9
    case .photoreal: return 10
    case .postage: return 11
    case .vintagePostage: return 12
    case .waxSeal: return 13
    case .rubberStamp: return 14
    case .engraved: return 15
    case .botanicalPostage: return 16
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AiartStyle] = [
    .unspecified,
    .anime,
    .cyberpunk,
    .watercolor,
    .pixelArt,
    .threeDCartoon,
    .fantasy,
    .oilPainting,
    .lineArt,
    .minimal,
    .photoreal,
    .postage,
    .vintagePostage,
    .waxSeal,
    .rubberStamp,
    .engraved,
    .botanicalPostage,
  ]

}

public enum AiartMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case normal // = 1
  case stamps // = 2
  case avatar // = 3
  case video // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .normal
    case 2: self = .stamps
    case 3: self = .avatar
    case 4: self = .video
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .normal: return 1
    case .stamps: return 2
    case .avatar: return 3
    case .video: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AiartMode] = [
    .unspecified,
    .normal,
    .stamps,
    .avatar,
    .video,
  ]

}

public struct AiartGenerateResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var images: [TypesImage] = []

  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  public var style: AiartStyle {
    get {_style ?? .unspecified}
    set {_style = newValue}
  }
  /// Returns true if `style` has been explicitly set.
  public var hasStyle: Bool {self._style != nil}
  /// Clears the value of `style`. Subsequent reads from it will return its default value.
  public mutating func clearStyle() {self._style = nil}

  public var providerTaskID: String {
    get {_providerTaskID ?? String()}
    set {_providerTaskID = newValue}
  }
  /// Returns true if `providerTaskID` has been explicitly set.
  public var hasProviderTaskID: Bool {self._providerTaskID != nil}
  /// Clears the value of `providerTaskID`. Subsequent reads from it will return its default value.
  public mutating func clearProviderTaskID() {self._providerTaskID = nil}

  public var metadata: SwiftProtobuf.Google_Protobuf_Struct {
    get {_metadata ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var aspectRatio: String {
    get {_aspectRatio ?? String()}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  public var width: UInt32 {
    get {_width ?? 0}
    set {_width = newValue}
  }
  /// Returns true if `width` has been explicitly set.
  public var hasWidth: Bool {self._width != nil}
  /// Clears the value of `width`. Subsequent reads from it will return its default value.
  public mutating func clearWidth() {self._width = nil}

  public var height: UInt32 {
    get {_height ?? 0}
    set {_height = newValue}
  }
  /// Returns true if `height` has been explicitly set.
  public var hasHeight: Bool {self._height != nil}
  /// Clears the value of `height`. Subsequent reads from it will return its default value.
  public mutating func clearHeight() {self._height = nil}

  public var mode: AiartMode {
    get {_mode ?? .unspecified}
    set {_mode = newValue}
  }
  /// Returns true if `mode` has been explicitly set.
  public var hasMode: Bool {self._mode != nil}
  /// Clears the value of `mode`. Subsequent reads from it will return its default value.
  public mutating func clearMode() {self._mode = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _prompt: String? = nil
  fileprivate var _style: AiartStyle? = nil
  fileprivate var _providerTaskID: String? = nil
  fileprivate var _metadata: SwiftProtobuf.Google_Protobuf_Struct? = nil
  fileprivate var _aspectRatio: String? = nil
  fileprivate var _width: UInt32? = nil
  fileprivate var _height: UInt32? = nil
  fileprivate var _mode: AiartMode? = nil
}

/// Result of a video generation pipeline (Character.AI Avatar FX).
/// RunAction returns this with video_id + task status=Processing.
/// GetStatus returns updated progress/status until COMPLETED or ERRORED.
public struct AiartVideoGenerateResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Request-level video ID used for polling status
  public var videoID: String = String()

  /// Final video URL (R2 signed, 7d expiry) — set when status=COMPLETED
  public var videoURL: String {
    get {_videoURL ?? String()}
    set {_videoURL = newValue}
  }
  /// Returns true if `videoURL` has been explicitly set.
  public var hasVideoURL: Bool {self._videoURL != nil}
  /// Clears the value of `videoURL`. Subsequent reads from it will return its default value.
  public mutating func clearVideoURL() {self._videoURL = nil}

  /// Pipeline status: QUEUED, PROCESSING, COMPLETED, ERRORED
  public var status: String {
    get {_status ?? String()}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {self._status = nil}

  /// Generation progress 0.0–1.0 (updated during PROCESSING)
  public var progress: Double {
    get {_progress ?? 0}
    set {_progress = newValue}
  }
  /// Returns true if `progress` has been explicitly set.
  public var hasProgress: Bool {self._progress != nil}
  /// Clears the value of `progress`. Subsequent reads from it will return its default value.
  public mutating func clearProgress() {self._progress = nil}

  /// Auto-generated prompt from image description step
  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  /// Style-transferred image URL produced during pipeline
  public var styledImageURL: String {
    get {_styledImageURL ?? String()}
    set {_styledImageURL = newValue}
  }
  /// Returns true if `styledImageURL` has been explicitly set.
  public var hasStyledImageURL: Bool {self._styledImageURL != nil}
  /// Clears the value of `styledImageURL`. Subsequent reads from it will return its default value.
  public mutating func clearStyledImageURL() {self._styledImageURL = nil}

  /// TTS audio URL produced during pipeline
  public var audioURL: String {
    get {_audioURL ?? String()}
    set {_audioURL = newValue}
  }
  /// Returns true if `audioURL` has been explicitly set.
  public var hasAudioURL: Bool {self._audioURL != nil}
  /// Clears the value of `audioURL`. Subsequent reads from it will return its default value.
  public mutating func clearAudioURL() {self._audioURL = nil}

  /// Art style applied (e.g. "Ghibli")
  public var artStyle: String {
    get {_artStyle ?? String()}
    set {_artStyle = newValue}
  }
  /// Returns true if `artStyle` has been explicitly set.
  public var hasArtStyle: Bool {self._artStyle != nil}
  /// Clears the value of `artStyle`. Subsequent reads from it will return its default value.
  public mutating func clearArtStyle() {self._artStyle = nil}

  public var metadata: SwiftProtobuf.Google_Protobuf_Struct {
    get {_metadata ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _videoURL: String? = nil
  fileprivate var _status: String? = nil
  fileprivate var _progress: Double? = nil
  fileprivate var _prompt: String? = nil
  fileprivate var _styledImageURL: String? = nil
  fileprivate var _audioURL: String? = nil
  fileprivate var _artStyle: String? = nil
  fileprivate var _metadata: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

/// Stamps mode (frame artwork with placeholder cutout). Plugins read
/// `prompt` for the figure description and may use plugin-specific
/// extras (stamp shape / placeholder size) the form drives.
public struct AiartStampRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var base: TypesBaseRequest {
    get {_base ?? TypesBaseRequest()}
    set {_base = newValue}
  }
  /// Returns true if `base` has been explicitly set.
  public var hasBase: Bool {self._base != nil}
  /// Clears the value of `base`. Subsequent reads from it will return its default value.
  public mutating func clearBase() {self._base = nil}

  /// Subject of the generation, e.g. "a fox in a cyberpunk city".
  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  /// Visual style preset.
  public var style: AiartStyle {
    get {_style ?? .unspecified}
    set {_style = newValue}
  }
  /// Returns true if `style` has been explicitly set.
  public var hasStyle: Bool {self._style != nil}
  /// Clears the value of `style`. Subsequent reads from it will return its default value.
  public mutating func clearStyle() {self._style = nil}

  /// Reference image URL — http(s)/data URI/file URL the provider
  /// downloads. Mutually exclusive with `image_path`.
  public var imageURL: String {
    get {_imageURL ?? String()}
    set {_imageURL = newValue}
  }
  /// Returns true if `imageURL` has been explicitly set.
  public var hasImageURL: Bool {self._imageURL != nil}
  /// Clears the value of `imageURL`. Subsequent reads from it will return its default value.
  public mutating func clearImageURL() {self._imageURL = nil}

  /// Local file path (file://) when the host already has the bytes
  /// staged. Mutually exclusive with `image_url`.
  public var imagePath: String {
    get {_imagePath ?? String()}
    set {_imagePath = newValue}
  }
  /// Returns true if `imagePath` has been explicitly set.
  public var hasImagePath: Bool {self._imagePath != nil}
  /// Clears the value of `imagePath`. Subsequent reads from it will return its default value.
  public mutating func clearImagePath() {self._imagePath = nil}

  /// Provider model id (e.g. "fal-ai/flux-pro"). Plugin's default
  /// applies when empty.
  public var model: String {
    get {_model ?? String()}
    set {_model = newValue}
  }
  /// Returns true if `model` has been explicitly set.
  public var hasModel: Bool {self._model != nil}
  /// Clears the value of `model`. Subsequent reads from it will return its default value.
  public mutating func clearModel() {self._model = nil}

  /// Per-model aspect-ratio string (e.g. "1:1", "16:9"). Plugin
  /// default applies when empty. Discovered values per model live
  /// in `ListModelsResponse.models[].metadata["aspect_ratios"]`.
  public var aspectRatio: String {
    get {_aspectRatio ?? String()}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  /// Number-of-images hint as a string (matches the existing dict path).
  public var numImages: String {
    get {_numImages ?? String()}
    set {_numImages = newValue}
  }
  /// Returns true if `numImages` has been explicitly set.
  public var hasNumImages: Bool {self._numImages != nil}
  /// Clears the value of `numImages`. Subsequent reads from it will return its default value.
  public mutating func clearNumImages() {self._numImages = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _base: TypesBaseRequest? = nil
  fileprivate var _prompt: String? = nil
  fileprivate var _style: AiartStyle? = nil
  fileprivate var _imageURL: String? = nil
  fileprivate var _imagePath: String? = nil
  fileprivate var _model: String? = nil
  fileprivate var _aspectRatio: String? = nil
  fileprivate var _numImages: String? = nil
}

/// Normal mode (full image generation). Same fields as Stamp; the
/// plugin's mode selection drives the system-prompt + endpoint.
public struct AiartNormalRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var base: TypesBaseRequest {
    get {_base ?? TypesBaseRequest()}
    set {_base = newValue}
  }
  /// Returns true if `base` has been explicitly set.
  public var hasBase: Bool {self._base != nil}
  /// Clears the value of `base`. Subsequent reads from it will return its default value.
  public mutating func clearBase() {self._base = nil}

  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  public var style: AiartStyle {
    get {_style ?? .unspecified}
    set {_style = newValue}
  }
  /// Returns true if `style` has been explicitly set.
  public var hasStyle: Bool {self._style != nil}
  /// Clears the value of `style`. Subsequent reads from it will return its default value.
  public mutating func clearStyle() {self._style = nil}

  public var imageURL: String {
    get {_imageURL ?? String()}
    set {_imageURL = newValue}
  }
  /// Returns true if `imageURL` has been explicitly set.
  public var hasImageURL: Bool {self._imageURL != nil}
  /// Clears the value of `imageURL`. Subsequent reads from it will return its default value.
  public mutating func clearImageURL() {self._imageURL = nil}

  public var imagePath: String {
    get {_imagePath ?? String()}
    set {_imagePath = newValue}
  }
  /// Returns true if `imagePath` has been explicitly set.
  public var hasImagePath: Bool {self._imagePath != nil}
  /// Clears the value of `imagePath`. Subsequent reads from it will return its default value.
  public mutating func clearImagePath() {self._imagePath = nil}

  public var model: String {
    get {_model ?? String()}
    set {_model = newValue}
  }
  /// Returns true if `model` has been explicitly set.
  public var hasModel: Bool {self._model != nil}
  /// Clears the value of `model`. Subsequent reads from it will return its default value.
  public mutating func clearModel() {self._model = nil}

  public var aspectRatio: String {
    get {_aspectRatio ?? String()}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  public var numImages: String {
    get {_numImages ?? String()}
    set {_numImages = newValue}
  }
  /// Returns true if `numImages` has been explicitly set.
  public var hasNumImages: Bool {self._numImages != nil}
  /// Clears the value of `numImages`. Subsequent reads from it will return its default value.
  public mutating func clearNumImages() {self._numImages = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _base: TypesBaseRequest? = nil
  fileprivate var _prompt: String? = nil
  fileprivate var _style: AiartStyle? = nil
  fileprivate var _imageURL: String? = nil
  fileprivate var _imagePath: String? = nil
  fileprivate var _model: String? = nil
  fileprivate var _aspectRatio: String? = nil
  fileprivate var _numImages: String? = nil
}

/// Avatar mode (head-and-shoulders portrait). Same field set as
/// Normal; only the system prompt differs in the executor.
public struct AiartAvatarRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var base: TypesBaseRequest {
    get {_base ?? TypesBaseRequest()}
    set {_base = newValue}
  }
  /// Returns true if `base` has been explicitly set.
  public var hasBase: Bool {self._base != nil}
  /// Clears the value of `base`. Subsequent reads from it will return its default value.
  public mutating func clearBase() {self._base = nil}

  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  public var style: AiartStyle {
    get {_style ?? .unspecified}
    set {_style = newValue}
  }
  /// Returns true if `style` has been explicitly set.
  public var hasStyle: Bool {self._style != nil}
  /// Clears the value of `style`. Subsequent reads from it will return its default value.
  public mutating func clearStyle() {self._style = nil}

  public var imageURL: String {
    get {_imageURL ?? String()}
    set {_imageURL = newValue}
  }
  /// Returns true if `imageURL` has been explicitly set.
  public var hasImageURL: Bool {self._imageURL != nil}
  /// Clears the value of `imageURL`. Subsequent reads from it will return its default value.
  public mutating func clearImageURL() {self._imageURL = nil}

  public var imagePath: String {
    get {_imagePath ?? String()}
    set {_imagePath = newValue}
  }
  /// Returns true if `imagePath` has been explicitly set.
  public var hasImagePath: Bool {self._imagePath != nil}
  /// Clears the value of `imagePath`. Subsequent reads from it will return its default value.
  public mutating func clearImagePath() {self._imagePath = nil}

  public var model: String {
    get {_model ?? String()}
    set {_model = newValue}
  }
  /// Returns true if `model` has been explicitly set.
  public var hasModel: Bool {self._model != nil}
  /// Clears the value of `model`. Subsequent reads from it will return its default value.
  public mutating func clearModel() {self._model = nil}

  public var aspectRatio: String {
    get {_aspectRatio ?? String()}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  public var numImages: String {
    get {_numImages ?? String()}
    set {_numImages = newValue}
  }
  /// Returns true if `numImages` has been explicitly set.
  public var hasNumImages: Bool {self._numImages != nil}
  /// Clears the value of `numImages`. Subsequent reads from it will return its default value.
  public mutating func clearNumImages() {self._numImages = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _base: TypesBaseRequest? = nil
  fileprivate var _prompt: String? = nil
  fileprivate var _style: AiartStyle? = nil
  fileprivate var _imageURL: String? = nil
  fileprivate var _imagePath: String? = nil
  fileprivate var _model: String? = nil
  fileprivate var _aspectRatio: String? = nil
  fileprivate var _numImages: String? = nil
}

/// Per-mode model discovery — replaces the metadata-driven
/// `model_infos`/`default_model` lookup off the Action descriptor.
/// Returns the active provider's model list for `mode` plus the
/// suggested default id. Each `ModelInfo.metadata["aspect_ratios"]`
/// carries the per-model aspect-ratio list so the UI can render the
/// ratio picker filtered by the selected model.
public struct AiartListModelsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var base: TypesBaseRequest {
    get {_base ?? TypesBaseRequest()}
    set {_base = newValue}
  }
  /// Returns true if `base` has been explicitly set.
  public var hasBase: Bool {self._base != nil}
  /// Clears the value of `base`. Subsequent reads from it will return its default value.
  public mutating func clearBase() {self._base = nil}

  /// Which mode's model list to return.
  public var mode: AiartMode {
    get {_mode ?? .unspecified}
    set {_mode = newValue}
  }
  /// Returns true if `mode` has been explicitly set.
  public var hasMode: Bool {self._mode != nil}
  /// Clears the value of `mode`. Subsequent reads from it will return its default value.
  public mutating func clearMode() {self._mode = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _base: TypesBaseRequest? = nil
  fileprivate var _mode: AiartMode? = nil
}

public struct AiartListModelsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var models: [TypesModelInfo] = []

  public var defaultModelID: String {
    get {_defaultModelID ?? String()}
    set {_defaultModelID = newValue}
  }
  /// Returns true if `defaultModelID` has been explicitly set.
  public var hasDefaultModelID: Bool {self._defaultModelID != nil}
  /// Clears the value of `defaultModelID`. Subsequent reads from it will return its default value.
  public mutating func clearDefaultModelID() {self._defaultModelID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _defaultModelID: String? = nil
}

/// Video generation (Character.AI Avatar FX pipeline). The host calls
/// `create()` for this rpc and polls via `getStatus` — `Video` is
/// `skip_flow_kit` so the plugin doesn't emit a typed wrapper.
public struct AiartVideoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var base: TypesBaseRequest {
    get {_base ?? TypesBaseRequest()}
    set {_base = newValue}
  }
  /// Returns true if `base` has been explicitly set.
  public var hasBase: Bool {self._base != nil}
  /// Clears the value of `base`. Subsequent reads from it will return its default value.
  public mutating func clearBase() {self._base = nil}

  /// Local file path (file://) of the source image — the pipeline
  /// describes it, style-transfers it, and animates the result.
  public var imagePath: String {
    get {_imagePath ?? String()}
    set {_imagePath = newValue}
  }
  /// Returns true if `imagePath` has been explicitly set.
  public var hasImagePath: Bool {self._imagePath != nil}
  /// Clears the value of `imagePath`. Subsequent reads from it will return its default value.
  public mutating func clearImagePath() {self._imagePath = nil}

  /// Display name of the art style preset (e.g. "Ghibli").
  public var artStyle: String {
    get {_artStyle ?? String()}
    set {_artStyle = newValue}
  }
  /// Returns true if `artStyle` has been explicitly set.
  public var hasArtStyle: Bool {self._artStyle != nil}
  /// Clears the value of `artStyle`. Subsequent reads from it will return its default value.
  public mutating func clearArtStyle() {self._artStyle = nil}

  /// Optional caller-supplied audio path; empty = the pipeline runs
  /// its own TTS step to generate audio from the auto-prompt.
  public var audioPath: String {
    get {_audioPath ?? String()}
    set {_audioPath = newValue}
  }
  /// Returns true if `audioPath` has been explicitly set.
  public var hasAudioPath: Bool {self._audioPath != nil}
  /// Clears the value of `audioPath`. Subsequent reads from it will return its default value.
  public mutating func clearAudioPath() {self._audioPath = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _base: TypesBaseRequest? = nil
  fileprivate var _imagePath: String? = nil
  fileprivate var _artStyle: String? = nil
  fileprivate var _audioPath: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.aiart"

extension AiartStyle: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STYLE_UNSPECIFIED\0\u{1}ANIME\0\u{1}CYBERPUNK\0\u{1}WATERCOLOR\0\u{1}PIXEL_ART\0\u{1}THREE_D_CARTOON\0\u{1}FANTASY\0\u{1}OIL_PAINTING\0\u{1}LINE_ART\0\u{1}MINIMAL\0\u{1}PHOTOREAL\0\u{1}POSTAGE\0\u{1}VINTAGE_POSTAGE\0\u{1}WAX_SEAL\0\u{1}RUBBER_STAMP\0\u{1}ENGRAVED\0\u{1}BOTANICAL_POSTAGE\0")
}

extension AiartMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MODE_UNSPECIFIED\0\u{1}NORMAL\0\u{1}STAMPS\0\u{1}AVATAR\0\u{1}VIDEO\0")
}

extension AiartGenerateResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenerateResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}images\0\u{1}prompt\0\u{1}style\0\u{3}provider_task_id\0\u{1}metadata\0\u{3}aspect_ratio\0\u{1}width\0\u{1}height\0\u{1}mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.images) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._style) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._providerTaskID) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._aspectRatio) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._width) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self._height) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self._mode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.images.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.images, fieldNumber: 1)
    }
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._style {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._providerTaskID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._aspectRatio {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._width {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._height {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._mode {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartGenerateResult, 
rhs: AiartGenerateResult
) -> Bool {
    if lhs.images != rhs.images {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._style != rhs._style {return false}
    if lhs._providerTaskID != rhs._providerTaskID {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._width != rhs._width {return false}
    if lhs._height != rhs._height {return false}
    if lhs._mode != rhs._mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartVideoGenerateResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoGenerateResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}video_id\0\u{3}video_url\0\u{1}status\0\u{1}progress\0\u{1}prompt\0\u{3}styled_image_url\0\u{3}audio_url\0\u{3}art_style\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.videoID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._videoURL) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._status) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._progress) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._styledImageURL) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._audioURL) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._artStyle) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.videoID.isEmpty {
      try visitor.visitSingularStringField(value: self.videoID, fieldNumber: 1)
    }
    try { if let v = self._videoURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._status {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._progress {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._styledImageURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._audioURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._artStyle {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartVideoGenerateResult, 
rhs: AiartVideoGenerateResult
) -> Bool {
    if lhs.videoID != rhs.videoID {return false}
    if lhs._videoURL != rhs._videoURL {return false}
    if lhs._status != rhs._status {return false}
    if lhs._progress != rhs._progress {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._styledImageURL != rhs._styledImageURL {return false}
    if lhs._audioURL != rhs._audioURL {return false}
    if lhs._artStyle != rhs._artStyle {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartStampRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StampRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}base\0\u{1}prompt\0\u{1}style\0\u{1}image_url\0\u{1}image_path\0\u{1}model\0\u{1}aspect_ratio\0\u{1}num_images\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._base) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._style) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._imageURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._imagePath) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._model) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._aspectRatio) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._numImages) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._base {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._style {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._imageURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._imagePath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._model {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._aspectRatio {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._numImages {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartStampRequest, 
rhs: AiartStampRequest
) -> Bool {
    if lhs._base != rhs._base {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._style != rhs._style {return false}
    if lhs._imageURL != rhs._imageURL {return false}
    if lhs._imagePath != rhs._imagePath {return false}
    if lhs._model != rhs._model {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._numImages != rhs._numImages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartNormalRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NormalRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}base\0\u{1}prompt\0\u{1}style\0\u{1}image_url\0\u{1}image_path\0\u{1}model\0\u{1}aspect_ratio\0\u{1}num_images\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._base) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._style) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._imageURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._imagePath) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._model) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._aspectRatio) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._numImages) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._base {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._style {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._imageURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._imagePath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._model {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._aspectRatio {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._numImages {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartNormalRequest, 
rhs: AiartNormalRequest
) -> Bool {
    if lhs._base != rhs._base {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._style != rhs._style {return false}
    if lhs._imageURL != rhs._imageURL {return false}
    if lhs._imagePath != rhs._imagePath {return false}
    if lhs._model != rhs._model {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._numImages != rhs._numImages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartAvatarRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AvatarRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}base\0\u{1}prompt\0\u{1}style\0\u{1}image_url\0\u{1}image_path\0\u{1}model\0\u{1}aspect_ratio\0\u{1}num_images\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._base) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._style) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._imageURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._imagePath) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._model) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._aspectRatio) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._numImages) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._base {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._style {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._imageURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._imagePath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._model {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._aspectRatio {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._numImages {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartAvatarRequest, 
rhs: AiartAvatarRequest
) -> Bool {
    if lhs._base != rhs._base {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._style != rhs._style {return false}
    if lhs._imageURL != rhs._imageURL {return false}
    if lhs._imagePath != rhs._imagePath {return false}
    if lhs._model != rhs._model {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._numImages != rhs._numImages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartListModelsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListModelsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}base\0\u{1}mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._base) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._mode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._base {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._mode {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartListModelsRequest, 
rhs: AiartListModelsRequest
) -> Bool {
    if lhs._base != rhs._base {return false}
    if lhs._mode != rhs._mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartListModelsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListModelsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}models\0\u{1}default_model_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.models) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._defaultModelID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.models.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.models, fieldNumber: 1)
    }
    try { if let v = self._defaultModelID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartListModelsResponse, 
rhs: AiartListModelsResponse
) -> Bool {
    if lhs.models != rhs.models {return false}
    if lhs._defaultModelID != rhs._defaultModelID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AiartVideoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}base\0\u{1}image_path\0\u{1}art_style\0\u{1}audio_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._base) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._imagePath) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._artStyle) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._audioPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._base {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._imagePath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._artStyle {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._audioPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: AiartVideoRequest, 
rhs: AiartVideoRequest
) -> Bool {
    if lhs._base != rhs._base {return false}
    if lhs._imagePath != rhs._imagePath {return false}
    if lhs._artStyle != rhs._artStyle {return false}
    if lhs._audioPath != rhs._audioPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
