// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: aiart.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf
#if canImport(FlowKit)
import FlowKit
#else
import WasmSwiftProtobuf
#endif

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum AiartStyle: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case anime // = 1
  case cyberpunk // = 2
  case watercolor // = 3
  case pixelArt // = 4
  case threeDCartoon // = 5
  case fantasy // = 6
  case oilPainting // = 7
  case lineArt // = 8
  case minimal // = 9
  case photoreal // = 10
  case postage // = 11
  case vintagePostage // = 12
  case waxSeal // = 13
  case rubberStamp // = 14
  case engraved // = 15
  case botanicalPostage // = 16
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .anime
    case 2: self = .cyberpunk
    case 3: self = .watercolor
    case 4: self = .pixelArt
    case 5: self = .threeDCartoon
    case 6: self = .fantasy
    case 7: self = .oilPainting
    case 8: self = .lineArt
    case 9: self = .minimal
    case 10: self = .photoreal
    case 11: self = .postage
    case 12: self = .vintagePostage
    case 13: self = .waxSeal
    case 14: self = .rubberStamp
    case 15: self = .engraved
    case 16: self = .botanicalPostage
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .anime: return 1
    case .cyberpunk: return 2
    case .watercolor: return 3
    case .pixelArt: return 4
    case .threeDCartoon: return 5
    case .fantasy: return 6
    case .oilPainting: return 7
    case .lineArt: return 8
    case .minimal: return 9
    case .photoreal: return 10
    case .postage: return 11
    case .vintagePostage: return 12
    case .waxSeal: return 13
    case .rubberStamp: return 14
    case .engraved: return 15
    case .botanicalPostage: return 16
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AiartStyle] = [
    .unspecified,
    .anime,
    .cyberpunk,
    .watercolor,
    .pixelArt,
    .threeDCartoon,
    .fantasy,
    .oilPainting,
    .lineArt,
    .minimal,
    .photoreal,
    .postage,
    .vintagePostage,
    .waxSeal,
    .rubberStamp,
    .engraved,
    .botanicalPostage,
  ]

}

public enum AiartMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case normal // = 1
  case stamps // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .normal
    case 2: self = .stamps
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .normal: return 1
    case .stamps: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AiartMode] = [
    .unspecified,
    .normal,
    .stamps,
  ]

}

public struct AiartGenerateResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var images: [TypesImage] = []

  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  public var style: AiartStyle {
    get {_style ?? .unspecified}
    set {_style = newValue}
  }
  /// Returns true if `style` has been explicitly set.
  public var hasStyle: Bool {self._style != nil}
  /// Clears the value of `style`. Subsequent reads from it will return its default value.
  public mutating func clearStyle() {self._style = nil}

  public var providerTaskID: String {
    get {_providerTaskID ?? String()}
    set {_providerTaskID = newValue}
  }
  /// Returns true if `providerTaskID` has been explicitly set.
  public var hasProviderTaskID: Bool {self._providerTaskID != nil}
  /// Clears the value of `providerTaskID`. Subsequent reads from it will return its default value.
  public mutating func clearProviderTaskID() {self._providerTaskID = nil}

  public var metadata: SwiftProtobuf.Google_Protobuf_Struct {
    get {_metadata ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var aspectRatio: String {
    get {_aspectRatio ?? String()}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  public var width: UInt32 {
    get {_width ?? 0}
    set {_width = newValue}
  }
  /// Returns true if `width` has been explicitly set.
  public var hasWidth: Bool {self._width != nil}
  /// Clears the value of `width`. Subsequent reads from it will return its default value.
  public mutating func clearWidth() {self._width = nil}

  public var height: UInt32 {
    get {_height ?? 0}
    set {_height = newValue}
  }
  /// Returns true if `height` has been explicitly set.
  public var hasHeight: Bool {self._height != nil}
  /// Clears the value of `height`. Subsequent reads from it will return its default value.
  public mutating func clearHeight() {self._height = nil}

  public var mode: AiartMode {
    get {_mode ?? .unspecified}
    set {_mode = newValue}
  }
  /// Returns true if `mode` has been explicitly set.
  public var hasMode: Bool {self._mode != nil}
  /// Clears the value of `mode`. Subsequent reads from it will return its default value.
  public mutating func clearMode() {self._mode = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _prompt: String? = nil
  fileprivate var _style: AiartStyle? = nil
  fileprivate var _providerTaskID: String? = nil
  fileprivate var _metadata: SwiftProtobuf.Google_Protobuf_Struct? = nil
  fileprivate var _aspectRatio: String? = nil
  fileprivate var _width: UInt32? = nil
  fileprivate var _height: UInt32? = nil
  fileprivate var _mode: AiartMode? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.aiart"

extension AiartStyle: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STYLE_UNSPECIFIED\0\u{1}ANIME\0\u{1}CYBERPUNK\0\u{1}WATERCOLOR\0\u{1}PIXEL_ART\0\u{1}THREE_D_CARTOON\0\u{1}FANTASY\0\u{1}OIL_PAINTING\0\u{1}LINE_ART\0\u{1}MINIMAL\0\u{1}PHOTOREAL\0\u{1}POSTAGE\0\u{1}VINTAGE_POSTAGE\0\u{1}WAX_SEAL\0\u{1}RUBBER_STAMP\0\u{1}ENGRAVED\0\u{1}BOTANICAL_POSTAGE\0")
}

extension AiartMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MODE_UNSPECIFIED\0\u{1}NORMAL\0\u{1}STAMPS\0")
}

extension AiartGenerateResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenerateResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}images\0\u{1}prompt\0\u{1}style\0\u{3}provider_task_id\0\u{1}metadata\0\u{3}aspect_ratio\0\u{1}width\0\u{1}height\0\u{1}mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.images) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._style) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._providerTaskID) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._aspectRatio) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._width) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self._height) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self._mode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.images.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.images, fieldNumber: 1)
    }
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._style {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._providerTaskID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._aspectRatio {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._width {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._height {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._mode {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AiartGenerateResult, rhs: AiartGenerateResult) -> Bool {
    if lhs.images != rhs.images {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._style != rhs._style {return false}
    if lhs._providerTaskID != rhs._providerTaskID {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._width != rhs._width {return false}
    if lhs._height != rhs._height {return false}
    if lhs._mode != rhs._mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
