// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: calories.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// Main food analysis result — normalized across all providers.
//// Returned by Analyze (text/image), Barcode, and Ingredient actions.
public struct CaloriesFoodResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Display name of the food (e.g. "Chicken Caesar Salad").
  public var name: String = String()

  //// Total calories in kcal for the analyzed portion.
  public var calories: Double = 0

  //// Total protein in grams.
  public var protein: Double = 0

  //// Total carbohydrates in grams.
  public var carbs: Double = 0

  //// Total fats in grams.
  public var fats: Double = 0

  //// Total sugar in grams (not all providers return this).
  public var sugar: Double {
    get {_sugar ?? 0}
    set {_sugar = newValue}
  }
  /// Returns true if `sugar` has been explicitly set.
  public var hasSugar: Bool {self._sugar != nil}
  /// Clears the value of `sugar`. Subsequent reads from it will return its default value.
  public mutating func clearSugar() {self._sugar = nil}

  //// Total dietary fiber in grams.
  public var fiber: Double {
    get {_fiber ?? 0}
    set {_fiber = newValue}
  }
  /// Returns true if `fiber` has been explicitly set.
  public var hasFiber: Bool {self._fiber != nil}
  /// Clears the value of `fiber`. Subsequent reads from it will return its default value.
  public mutating func clearFiber() {self._fiber = nil}

  //// Total sodium in milligrams.
  public var sodium: Double {
    get {_sodium ?? 0}
    set {_sodium = newValue}
  }
  /// Returns true if `sodium` has been explicitly set.
  public var hasSodium: Bool {self._sodium != nil}
  /// Clears the value of `sodium`. Subsequent reads from it will return its default value.
  public mutating func clearSodium() {self._sodium = nil}

  //// Number of servings the macros represent (e.g. 1.0 = single serving).
  public var servings: Double {
    get {_servings ?? 0}
    set {_servings = newValue}
  }
  /// Returns true if `servings` has been explicitly set.
  public var hasServings: Bool {self._servings != nil}
  /// Clears the value of `servings`. Subsequent reads from it will return its default value.
  public mutating func clearServings() {self._servings = nil}

  //// Provider's healthiness rating on a 1-10 scale (higher = healthier).
  public var healthScore: Int32 {
    get {_healthScore ?? 0}
    set {_healthScore = newValue}
  }
  /// Returns true if `healthScore` has been explicitly set.
  public var hasHealthScore: Bool {self._healthScore != nil}
  /// Clears the value of `healthScore`. Subsequent reads from it will return its default value.
  public mutating func clearHealthScore() {self._healthScore = nil}

  //// Breakdown of individual ingredients with per-ingredient macros.
  public var ingredients: [CaloriesIngredient] = []

  //// Provider-specific extra data not captured by typed fields.
  public var metadata: SwiftProtobuf.Google_Protobuf_Struct {
    get {_metadata ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sugar: Double? = nil
  fileprivate var _fiber: Double? = nil
  fileprivate var _sodium: Double? = nil
  fileprivate var _servings: Double? = nil
  fileprivate var _healthScore: Int32? = nil
  fileprivate var _metadata: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

//// A single ingredient within a FoodResult breakdown.
public struct CaloriesIngredient: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Ingredient name (e.g. "romaine lettuce", "grilled chicken").
  public var name: String = String()

  //// Calories in kcal for this ingredient's portion.
  public var calories: Double = 0

  //// Protein in grams.
  public var protein: Double = 0

  //// Carbohydrates in grams.
  public var carbs: Double = 0

  //// Fats in grams.
  public var fats: Double = 0

  //// Quantity of this ingredient (e.g. 150.0 for 150g).
  public var amount: Double {
    get {_amount ?? 0}
    set {_amount = newValue}
  }
  /// Returns true if `amount` has been explicitly set.
  public var hasAmount: Bool {self._amount != nil}
  /// Clears the value of `amount`. Subsequent reads from it will return its default value.
  public mutating func clearAmount() {self._amount = nil}

  //// Unit of the amount (e.g. "g", "ml", "oz", "cup").
  public var unit: String {
    get {_unit ?? String()}
    set {_unit = newValue}
  }
  /// Returns true if `unit` has been explicitly set.
  public var hasUnit: Bool {self._unit != nil}
  /// Clears the value of `unit`. Subsequent reads from it will return its default value.
  public mutating func clearUnit() {self._unit = nil}

  //// Provider's confidence in this ingredient identification (0.0-1.0).
  public var confidence: Double {
    get {_confidence ?? 0}
    set {_confidence = newValue}
  }
  /// Returns true if `confidence` has been explicitly set.
  public var hasConfidence: Bool {self._confidence != nil}
  /// Clears the value of `confidence`. Subsequent reads from it will return its default value.
  public mutating func clearConfidence() {self._confidence = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _amount: Double? = nil
  fileprivate var _unit: String? = nil
  fileprivate var _confidence: Double? = nil
}

//// Health score / analytics result for a specific food item.
//// Returned by the Health Score action.
public struct CaloriesHealthScoreResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Overall health rating on a 1-10 scale (higher = healthier).
  public var rating: Int32 = 0

  //// Nutritional balance assessment (e.g. "Well-balanced", "High in carbs").
  public var balance: String = String()

  //// Satiety/fullness assessment (e.g. "Very filling", "Light meal").
  public var fullness: String = String()

  //// How well the food fits typical health goals (e.g. "Good for weight loss").
  public var goalFit: String = String()

  //// Summary message from the provider's analysis.
  public var message: String = String()

  //// Actionable improvement tips (e.g. "Add more vegetables", "Reduce sodium").
  public var tips: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

//// Search result containing a list of matching food items.
//// Returned by Search and Suggestions actions.
public struct CaloriesSearchResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// List of food items matching the query or suggestion criteria.
  public var items: [CaloriesFoodItem] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

//// A food item from search/suggestions — lighter than FoodResult.
//// Contains summary macros but no ingredient breakdown.
public struct CaloriesFoodItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Provider-specific unique identifier for this food item.
  public var id: String = String()

  //// Display name (e.g. "Banana", "Coca-Cola Classic 330ml").
  public var name: String = String()

  //// Calories in kcal per default serving.
  public var calories: Double = 0

  //// Protein in grams per default serving.
  public var protein: Double = 0

  //// Carbohydrates in grams per default serving.
  public var carbs: Double = 0

  //// Fats in grams per default serving.
  public var fats: Double = 0

  //// Brand name if this is a branded/packaged product.
  public var brand: String {
    get {_brand ?? String()}
    set {_brand = newValue}
  }
  /// Returns true if `brand` has been explicitly set.
  public var hasBrand: Bool {self._brand != nil}
  /// Clears the value of `brand`. Subsequent reads from it will return its default value.
  public mutating func clearBrand() {self._brand = nil}

  //// Available serving sizes with pre-calculated macros for each.
  public var servingTypes: [CaloriesServingType] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _brand: String? = nil
}

//// A specific serving size option for a food item.
//// Each serving type has pre-calculated macros for convenience.
public struct CaloriesServingType: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Provider-specific identifier for this serving type.
  public var id: String = String()

  //// Human-readable label (e.g. "1 cup", "100g", "1 medium").
  public var label: String = String()

  //// Numeric amount in the specified unit (e.g. 240.0 for 240ml).
  public var amount: Double = 0

  //// Unit of measurement (e.g. "g", "ml", "piece").
  public var unit: String = String()

  //// Calories in kcal for this serving size.
  public var calories: Double = 0

  //// Protein in grams for this serving size.
  public var protein: Double = 0

  //// Carbohydrates in grams for this serving size.
  public var carbs: Double = 0

  //// Fats in grams for this serving size.
  public var fats: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.calories"

extension CaloriesFoodResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FoodResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}calories\0\u{1}protein\0\u{1}carbs\0\u{1}fats\0\u{1}sugar\0\u{1}fiber\0\u{1}sodium\0\u{1}servings\0\u{3}health_score\0\u{1}ingredients\0\u{2}\u{4}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.calories) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.protein) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.carbs) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.fats) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._sugar) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._fiber) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self._sodium) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self._servings) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self._healthScore) }()
      case 11: try { try decoder.decodeRepeatedMessageField(value: &self.ingredients) }()
      case 15: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.calories.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.calories, fieldNumber: 2)
    }
    if self.protein.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.protein, fieldNumber: 3)
    }
    if self.carbs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.carbs, fieldNumber: 4)
    }
    if self.fats.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fats, fieldNumber: 5)
    }
    try { if let v = self._sugar {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._fiber {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._sodium {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._servings {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._healthScore {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 10)
    } }()
    if !self.ingredients.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ingredients, fieldNumber: 11)
    }
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CaloriesFoodResult, rhs: CaloriesFoodResult) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.calories != rhs.calories {return false}
    if lhs.protein != rhs.protein {return false}
    if lhs.carbs != rhs.carbs {return false}
    if lhs.fats != rhs.fats {return false}
    if lhs._sugar != rhs._sugar {return false}
    if lhs._fiber != rhs._fiber {return false}
    if lhs._sodium != rhs._sodium {return false}
    if lhs._servings != rhs._servings {return false}
    if lhs._healthScore != rhs._healthScore {return false}
    if lhs.ingredients != rhs.ingredients {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CaloriesIngredient: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Ingredient"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}calories\0\u{1}protein\0\u{1}carbs\0\u{1}fats\0\u{1}amount\0\u{1}unit\0\u{1}confidence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.calories) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.protein) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.carbs) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.fats) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._amount) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._unit) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self._confidence) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.calories.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.calories, fieldNumber: 2)
    }
    if self.protein.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.protein, fieldNumber: 3)
    }
    if self.carbs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.carbs, fieldNumber: 4)
    }
    if self.fats.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fats, fieldNumber: 5)
    }
    try { if let v = self._amount {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._unit {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._confidence {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CaloriesIngredient, rhs: CaloriesIngredient) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.calories != rhs.calories {return false}
    if lhs.protein != rhs.protein {return false}
    if lhs.carbs != rhs.carbs {return false}
    if lhs.fats != rhs.fats {return false}
    if lhs._amount != rhs._amount {return false}
    if lhs._unit != rhs._unit {return false}
    if lhs._confidence != rhs._confidence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CaloriesHealthScoreResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthScoreResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}rating\0\u{1}balance\0\u{1}fullness\0\u{3}goal_fit\0\u{1}message\0\u{1}tips\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.rating) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.balance) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fullness) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.goalFit) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.tips) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rating != 0 {
      try visitor.visitSingularInt32Field(value: self.rating, fieldNumber: 1)
    }
    if !self.balance.isEmpty {
      try visitor.visitSingularStringField(value: self.balance, fieldNumber: 2)
    }
    if !self.fullness.isEmpty {
      try visitor.visitSingularStringField(value: self.fullness, fieldNumber: 3)
    }
    if !self.goalFit.isEmpty {
      try visitor.visitSingularStringField(value: self.goalFit, fieldNumber: 4)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 5)
    }
    if !self.tips.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tips, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CaloriesHealthScoreResult, rhs: CaloriesHealthScoreResult) -> Bool {
    if lhs.rating != rhs.rating {return false}
    if lhs.balance != rhs.balance {return false}
    if lhs.fullness != rhs.fullness {return false}
    if lhs.goalFit != rhs.goalFit {return false}
    if lhs.message != rhs.message {return false}
    if lhs.tips != rhs.tips {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CaloriesSearchResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SearchResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}items\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CaloriesSearchResult, rhs: CaloriesSearchResult) -> Bool {
    if lhs.items != rhs.items {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CaloriesFoodItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FoodItem"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}calories\0\u{1}protein\0\u{1}carbs\0\u{1}fats\0\u{1}brand\0\u{3}serving_types\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.calories) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.protein) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.carbs) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.fats) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._brand) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.servingTypes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if self.calories.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.calories, fieldNumber: 3)
    }
    if self.protein.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.protein, fieldNumber: 4)
    }
    if self.carbs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.carbs, fieldNumber: 5)
    }
    if self.fats.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fats, fieldNumber: 6)
    }
    try { if let v = self._brand {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    if !self.servingTypes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.servingTypes, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CaloriesFoodItem, rhs: CaloriesFoodItem) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.calories != rhs.calories {return false}
    if lhs.protein != rhs.protein {return false}
    if lhs.carbs != rhs.carbs {return false}
    if lhs.fats != rhs.fats {return false}
    if lhs._brand != rhs._brand {return false}
    if lhs.servingTypes != rhs.servingTypes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CaloriesServingType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ServingType"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}label\0\u{1}amount\0\u{1}unit\0\u{1}calories\0\u{1}protein\0\u{1}carbs\0\u{1}fats\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.amount) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.unit) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.calories) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.protein) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.carbs) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.fats) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    if self.amount.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.amount, fieldNumber: 3)
    }
    if !self.unit.isEmpty {
      try visitor.visitSingularStringField(value: self.unit, fieldNumber: 4)
    }
    if self.calories.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.calories, fieldNumber: 5)
    }
    if self.protein.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.protein, fieldNumber: 6)
    }
    if self.carbs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.carbs, fieldNumber: 7)
    }
    if self.fats.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fats, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: CaloriesServingType, rhs: CaloriesServingType) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.label != rhs.label {return false}
    if lhs.amount != rhs.amount {return false}
    if lhs.unit != rhs.unit {return false}
    if lhs.calories != rhs.calories {return false}
    if lhs.protein != rhs.protein {return false}
    if lhs.carbs != rhs.carbs {return false}
    if lhs.fats != rhs.fats {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
