// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: homedecor.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf
#if canImport(FlowKit)
import FlowKit
#else
import WasmSwiftProtobuf
#endif

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum HomedecorProcessType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Full radical interior redesign (replace all furniture + decor)
  case interior // = 1

  /// Facade material swap only (keep building geometry)
  case exterior // = 2

  /// Landscape/vegetation redesign (keep hardscape)
  case garden // = 3

  /// Paint room walls/surfaces with color (HomeAI: needs mask + color)
  case paint // = 4

  /// Replace masked objects with prompt-described items (needs mask)
  case replace // = 5

  /// Floor material replacement only
  case floor // = 6

  /// Redesign using a second reference image as style guide (needs ref_image)
  case reference // = 7

  /// Add furniture + decor to empty/sparse room (keep architecture)
  case staging // = 8

  /// Remove clutter, clean surfaces (fixed prompt, no style)
  case declutter // = 9

  /// Generate 2D floor plan from photo (fixed prompt, no style)
  case floorPlan // = 10

  /// Render floor plan as photorealistic interior in chosen style
  case planToImage // = 11
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .interior
    case 2: self = .exterior
    case 3: self = .garden
    case 4: self = .paint
    case 5: self = .replace
    case 6: self = .floor
    case 7: self = .reference
    case 8: self = .staging
    case 9: self = .declutter
    case 10: self = .floorPlan
    case 11: self = .planToImage
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .interior: return 1
    case .exterior: return 2
    case .garden: return 3
    case .paint: return 4
    case .replace: return 5
    case .floor: return 6
    case .reference: return 7
    case .staging: return 8
    case .declutter: return 9
    case .floorPlan: return 10
    case .planToImage: return 11
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [HomedecorProcessType] = [
    .unspecified,
    .interior,
    .exterior,
    .garden,
    .paint,
    .replace,
    .floor,
    .reference,
    .staging,
    .declutter,
    .floorPlan,
    .planToImage,
  ]

}

public enum HomedecorStyleSelection: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Keep room structure, change style only (HomeAI/DecAI)
  case structuralPreservation // = 1

  /// Full renovation including structural changes
  case renovationDesign // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .structuralPreservation
    case 2: self = .renovationDesign
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .structuralPreservation: return 1
    case .renovationDesign: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [HomedecorStyleSelection] = [
    .unspecified,
    .structuralPreservation,
    .renovationDesign,
  ]

}

public enum HomedecorRoomType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Interior rooms
  case livingRoom // = 1
  case bedroom // = 2
  case kitchen // = 3
  case diningRoom // = 4
  case bathroom // = 5
  case office // = 6
  case homeOffice // = 7
  case studyRoom // = 8
  case attic // = 9
  case coffeeShop // = 10
  case gamingRoom // = 11
  case restaurant // = 12
  case toilet // = 13
  case balcony // = 14
  case hall // = 15
  case gardenRoom // = 16
  case deck // = 17
  case entryway // = 25
  case laundryRoom // = 26

  /// Exterior / building types
  case apartment // = 18
  case residential // = 19
  case house // = 20
  case retail // = 21
  case villa // = 22
  case underStairSpace // = 23
  case officeBuilding // = 24
  case tower // = 27
  case ranch // = 28
  case swimmingPool // = 29
  case yard // = 30
  case otherRoom // = 31
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .livingRoom
    case 2: self = .bedroom
    case 3: self = .kitchen
    case 4: self = .diningRoom
    case 5: self = .bathroom
    case 6: self = .office
    case 7: self = .homeOffice
    case 8: self = .studyRoom
    case 9: self = .attic
    case 10: self = .coffeeShop
    case 11: self = .gamingRoom
    case 12: self = .restaurant
    case 13: self = .toilet
    case 14: self = .balcony
    case 15: self = .hall
    case 16: self = .gardenRoom
    case 17: self = .deck
    case 18: self = .apartment
    case 19: self = .residential
    case 20: self = .house
    case 21: self = .retail
    case 22: self = .villa
    case 23: self = .underStairSpace
    case 24: self = .officeBuilding
    case 25: self = .entryway
    case 26: self = .laundryRoom
    case 27: self = .tower
    case 28: self = .ranch
    case 29: self = .swimmingPool
    case 30: self = .yard
    case 31: self = .otherRoom
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .livingRoom: return 1
    case .bedroom: return 2
    case .kitchen: return 3
    case .diningRoom: return 4
    case .bathroom: return 5
    case .office: return 6
    case .homeOffice: return 7
    case .studyRoom: return 8
    case .attic: return 9
    case .coffeeShop: return 10
    case .gamingRoom: return 11
    case .restaurant: return 12
    case .toilet: return 13
    case .balcony: return 14
    case .hall: return 15
    case .gardenRoom: return 16
    case .deck: return 17
    case .apartment: return 18
    case .residential: return 19
    case .house: return 20
    case .retail: return 21
    case .villa: return 22
    case .underStairSpace: return 23
    case .officeBuilding: return 24
    case .entryway: return 25
    case .laundryRoom: return 26
    case .tower: return 27
    case .ranch: return 28
    case .swimmingPool: return 29
    case .yard: return 30
    case .otherRoom: return 31
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [HomedecorRoomType] = [
    .unspecified,
    .livingRoom,
    .bedroom,
    .kitchen,
    .diningRoom,
    .bathroom,
    .office,
    .homeOffice,
    .studyRoom,
    .attic,
    .coffeeShop,
    .gamingRoom,
    .restaurant,
    .toilet,
    .balcony,
    .hall,
    .gardenRoom,
    .deck,
    .entryway,
    .laundryRoom,
    .apartment,
    .residential,
    .house,
    .retail,
    .villa,
    .underStairSpace,
    .officeBuilding,
    .tower,
    .ranch,
    .swimmingPool,
    .yard,
    .otherRoom,
  ]

}

/// Provider key: R=ReRoom, H=HomeAI, D=DecAI
/// Interior mapping shown; ext: prefix = exterior/garden only
/// Preview: HomeAI CDN thumbnails (R and D have no discoverable preview API)
public enum HomedecorRoomStyle: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// R:"modern"  H:"1",ext:"modernStyle"  D:"10",ext:"24"
  /// https://cdn.homeinterior.ai/assets/thumbnail_modernlivingroom_3a2f0f51ad/thumbnail_modernlivingroom_3a2f0f51ad.png
  case modern // = 1

  /// R:"tropical"  H:"2"  D:"97",ext:"123"
  /// https://cdn.homeinterior.ai/assets/thumbnail_tropicalbathroom_e020eb66cd/thumbnail_tropicalbathroom_e020eb66cd.png
  case tropical // = 2

  /// R:"minimalism"  H:"5",ext:"minimalisticStyle"  D:"11",ext:"26"
  /// https://cdn.homeinterior.ai/assets/thumbnail_minimalisticdiningroom_482a4618a8/thumbnail_minimalisticdiningroom_482a4618a8.png
  case minimalist // = 3

  /// R:"freespirit"  H:"9"  D:"5"
  /// https://cdn.homeinterior.ai/assets/thumbnail_bohemainhomeoofice_235aa67d2f/thumbnail_bohemainhomeoofice_235aa67d2f.png
  case bohemian // = 4

  /// R:"nomad"  H:"10"  D:"95",ext:"126"
  /// https://cdn.homeinterior.ai/assets/thumbnail_rustickitchen_45b8feb798/thumbnail_rustickitchen_45b8feb798.png
  case rustic // = 5

  /// R:"retro"  H:"11"  D:"12"
  /// https://cdn.homeinterior.ai/assets/thumbnail_vintageoffice_6a2a7172dc/thumbnail_vintageoffice_6a2a7172dc.png
  case vintage // = 6

  /// R:"grandeur"  H:"12"  D:"79"
  /// https://cdn.homeinterior.ai/assets/thumbnail_baroquelivingroom_5f6510a09e/thumbnail_baroquelivingroom_5f6510a09e.png
  case baroque // = 7

  /// R:"mediterranean"  H:"13",ext:"mediterraneanStyle"  D:"121",ext:"28"
  /// https://cdn.homeinterior.ai/assets/thumbnail_Mediterraneanlivingroom_979a7ad1e3/thumbnail_Mediterraneanlivingroom_979a7ad1e3.png
  case mediterranean // = 8

  /// R:"neon"  H:"14"  D:"111"
  /// https://cdn.homeinterior.ai/assets/thumbnail_cyberpunkgamingroom_5b28551433/thumbnail_cyberpunkgamingroom_5b28551433.png
  case cyberpunk // = 9

  /// R:"nature"  H:"16"  D:"93"
  /// https://cdn.homeinterior.ai/assets/thumbnail_biophilicrestaurant_02a79e64c9/thumbnail_biophilicrestaurant_02a79e64c9.png
  case biophilic // = 10

  /// H:"17"
  /// https://cdn.homeinterior.ai/assets/thumbnail_ancientegyptiandiningroom_ad04ea83dd/thumbnail_ancientegyptiandiningroom_ad04ea83dd.png
  case ancientEgyptian // = 11

  /// H:"19"  D:"91"
  /// https://cdn.homeinterior.ai/assets/thumbnail_airbnbstudyroom_a9a9fa8fbc/thumbnail_airbnbstudyroom_a9a9fa8fbc.png
  case airbnb // = 12

  /// H:"21"
  /// https://cdn.homeinterior.ai/assets/thumbnail_Discothequebathroom_657c188f6c/thumbnail_Discothequebathroom_657c188f6c.png
  case discotheque // = 13

  /// H:"22"
  /// https://cdn.homeinterior.ai/assets/thumbnail_sohostylelivingroom_b485e61b9d/thumbnail_sohostylelivingroom_b485e61b9d.png
  case soho // = 14

  /// H:"23"  D:"119"
  /// https://cdn.homeinterior.ai/assets/thumbnail_rainbowkitchen_a908591def/thumbnail_rainbowkitchen_a908591def.png
  case rainbow // = 15

  /// R:"luxe"  H:"26"  D:"81",ext:"125"
  /// https://cdn.homeinterior.ai/assets/thumbnail_luxurybedroom_570b7ca576/thumbnail_luxurybedroom_570b7ca576.png
  case luxury // = 16

  /// H:"27"  D:"105"
  /// https://cdn.homeinterior.ai/assets/thumbnail_Techno_Wonderlandbedroom_530cdbb7a4/thumbnail_Techno_Wonderlandbedroom_530cdbb7a4.png
  case techno // = 17

  /// H:"28"
  /// https://cdn.homeinterior.ai/assets/thumbnail_gameingroomgamer_b01ccffe5c/thumbnail_gameingroomgamer_b01ccffe5c.png
  case gamer // = 18

  /// R:"oasis"  H:"29"  D:"89",ext:"128"
  /// https://cdn.homeinterior.ai/assets/thumbnail_cozylivingroom_cb12f0041e/thumbnail_cozylivingroom_cb12f0041e.png
  case cozy // = 19

  /// R:"coastal"  H:"31"  D:"99"
  /// https://cdn.homeinterior.ai/assets/thumbnail_Coastaldiningroom_b2d146bc62/thumbnail_Coastaldiningroom_b2d146bc62.png
  case coastal // = 20

  /// R:"japanese"  H:"33"  D:"1"
  /// https://cdn.homeinterior.ai/assets/thumbnail_japandibedroom_0a18b44b92/thumbnail_japandibedroom_0a18b44b92.png
  case japandi // = 21

  /// R:"english"  H:"35"
  /// https://cdn.homeinterior.ai/assets/thumbnail_cottagecorelivingroom_239d3f8b79/thumbnail_cottagecorelivingroom_239d3f8b79.png
  case cottagecore // = 22

  /// R:"oasis"  H:"36",ext:"skiChaletStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_skichaletattic_15a7bc225a/thumbnail_skichaletattic_15a7bc225a.png
  case skiChalet // = 23

  /// R:"heritage"  H:"37",ext:"gothicStyle"  D:"87"
  /// https://cdn.homeinterior.ai/assets/thumbnail_gothicstudyroom_9cdfc7adab/thumbnail_gothicstudyroom_9cdfc7adab.png
  case gothic // = 24

  /// H:"38"  D:"103"
  /// https://cdn.homeinterior.ai/assets/thumbnail_creepyofficemin_5e7be1a322/thumbnail_creepyofficemin_5e7be1a322.png
  case creepy // = 25

  /// H:"39"  D:"113"
  /// https://cdn.homeinterior.ai/assets/thumbnail_medivaldiningroom_a223be5f04/thumbnail_medivaldiningroom_a223be5f04.png
  case medieval // = 26

  /// H:"41"
  /// https://cdn.homeinterior.ai/assets/thumbnail_80skitchen_1c19bb1e43/thumbnail_80skitchen_1c19bb1e43.png
  case eighties // = 27

  /// H:"42"  D:"109"
  /// https://cdn.homeinterior.ai/assets/thumbnail_cartooncoffeshop_e7642d8650/thumbnail_cartooncoffeshop_e7642d8650.png
  case cartoon // = 28

  /// H:"43"
  /// https://cdn.homeinterior.ai/assets/thumbnail_woodkitchen_5d588f2af9/thumbnail_woodkitchen_5d588f2af9.png
  case wood // = 29

  /// H:"44"
  /// https://cdn.homeinterior.ai/assets/thumbnail_chocolatelivingroom_215239d630/thumbnail_chocolatelivingroom_215239d630.png
  case chocolate // = 30

  /// H:ext:"italianateStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_italianate_0b89b166fb/thumbnail_italianate_0b89b166fb.png
  case italianate // = 31

  /// H:ext:"brutalistStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_brutalist_828a09c9c9/thumbnail_brutalist_828a09c9c9.png
  case brutalist // = 32

  /// R:"victorian"  H:ext:"artDecoStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_art_deco_b3e8c7b48e/thumbnail_art_deco_b3e8c7b48e.png
  case artDeco // = 33

  /// H:ext:"chineseStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_chinese_565b1f487e/thumbnail_chinese_565b1f487e.png
  case chinese // = 34

  /// R:"japanese"  H:ext:"japaneseStyle"  D:"4"
  /// https://cdn.homeinterior.ai/assets/thumbnail_japanese_9242ac2d7d/thumbnail_japanese_9242ac2d7d.png
  case japanese // = 35

  /// R:"english"  H:ext:"cottageStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_cottage_f524e469d1/thumbnail_cottage_f524e469d1.png
  case cottage // = 36

  /// H:ext:"spanishStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_spanish_84174a2842/thumbnail_spanish_84174a2842.png
  case spanish // = 37

  /// H:ext:"moroccoStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_morocco_22cbc1cc6d/thumbnail_morocco_22cbc1cc6d.png
  case morocco // = 38

  /// R:"midcenturymodern"  H:ext:"midcenturyStyle"  D:"13",ext:"29"
  /// https://cdn.homeinterior.ai/assets/thumbnail_midcentury_696458084b/thumbnail_midcentury_696458084b.png
  case midcentury // = 39

  /// H:ext:"middleEasternStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_middle_eastern_a778b48b80/thumbnail_middle_eastern_a778b48b80.png
  case middleEastern // = 40

  /// R:"nomad"  H:ext:"farmHouseStyle"  D:"6",ext:"27"
  /// https://cdn.homeinterior.ai/assets/thumbnail_farmhouse_8f4e2759e1/thumbnail_farmhouse_8f4e2759e1.png
  case farmhouse // = 41

  /// R:"english"  H:ext:"frenchStyle"
  /// https://cdn.homeinterior.ai/assets/thumbnail_french_587a92aa1f/thumbnail_french_587a92aa1f.png
  case french // = 42

  /// H:ext:"christmasStyle"  D:"45",ext:"47"
  /// https://cdn.homeinterior.ai/assets/thumbnail_image_15_675eb12b04/thumbnail_image_15_675eb12b04.png
  case christmas // = 43

  /// R:"industrial"  D:"2"
  case industrial // = 44

  /// R:"scandinavian"  D:"7"
  case scandinavian // = 45

  /// D:"20",ext:"25"
  case noStyle // = 46

  /// R:"nature"  D:"22",ext:"35"
  case zen // = 47

  /// D:"115"
  case halloween // = 48

  /// D:"117"
  case concrete // = 49

  /// R:"retro"  D:ext:"130"
  case retro // = 50

  /// R:"beachhouse"
  case beachHouse // = 51

  /// R:"isle"
  case isle // = 52

  /// R:"stValentinesDay"
  case stValentinesDay // = 53
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .modern
    case 2: self = .tropical
    case 3: self = .minimalist
    case 4: self = .bohemian
    case 5: self = .rustic
    case 6: self = .vintage
    case 7: self = .baroque
    case 8: self = .mediterranean
    case 9: self = .cyberpunk
    case 10: self = .biophilic
    case 11: self = .ancientEgyptian
    case 12: self = .airbnb
    case 13: self = .discotheque
    case 14: self = .soho
    case 15: self = .rainbow
    case 16: self = .luxury
    case 17: self = .techno
    case 18: self = .gamer
    case 19: self = .cozy
    case 20: self = .coastal
    case 21: self = .japandi
    case 22: self = .cottagecore
    case 23: self = .skiChalet
    case 24: self = .gothic
    case 25: self = .creepy
    case 26: self = .medieval
    case 27: self = .eighties
    case 28: self = .cartoon
    case 29: self = .wood
    case 30: self = .chocolate
    case 31: self = .italianate
    case 32: self = .brutalist
    case 33: self = .artDeco
    case 34: self = .chinese
    case 35: self = .japanese
    case 36: self = .cottage
    case 37: self = .spanish
    case 38: self = .morocco
    case 39: self = .midcentury
    case 40: self = .middleEastern
    case 41: self = .farmhouse
    case 42: self = .french
    case 43: self = .christmas
    case 44: self = .industrial
    case 45: self = .scandinavian
    case 46: self = .noStyle
    case 47: self = .zen
    case 48: self = .halloween
    case 49: self = .concrete
    case 50: self = .retro
    case 51: self = .beachHouse
    case 52: self = .isle
    case 53: self = .stValentinesDay
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .modern: return 1
    case .tropical: return 2
    case .minimalist: return 3
    case .bohemian: return 4
    case .rustic: return 5
    case .vintage: return 6
    case .baroque: return 7
    case .mediterranean: return 8
    case .cyberpunk: return 9
    case .biophilic: return 10
    case .ancientEgyptian: return 11
    case .airbnb: return 12
    case .discotheque: return 13
    case .soho: return 14
    case .rainbow: return 15
    case .luxury: return 16
    case .techno: return 17
    case .gamer: return 18
    case .cozy: return 19
    case .coastal: return 20
    case .japandi: return 21
    case .cottagecore: return 22
    case .skiChalet: return 23
    case .gothic: return 24
    case .creepy: return 25
    case .medieval: return 26
    case .eighties: return 27
    case .cartoon: return 28
    case .wood: return 29
    case .chocolate: return 30
    case .italianate: return 31
    case .brutalist: return 32
    case .artDeco: return 33
    case .chinese: return 34
    case .japanese: return 35
    case .cottage: return 36
    case .spanish: return 37
    case .morocco: return 38
    case .midcentury: return 39
    case .middleEastern: return 40
    case .farmhouse: return 41
    case .french: return 42
    case .christmas: return 43
    case .industrial: return 44
    case .scandinavian: return 45
    case .noStyle: return 46
    case .zen: return 47
    case .halloween: return 48
    case .concrete: return 49
    case .retro: return 50
    case .beachHouse: return 51
    case .isle: return 52
    case .stValentinesDay: return 53
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [HomedecorRoomStyle] = [
    .unspecified,
    .modern,
    .tropical,
    .minimalist,
    .bohemian,
    .rustic,
    .vintage,
    .baroque,
    .mediterranean,
    .cyberpunk,
    .biophilic,
    .ancientEgyptian,
    .airbnb,
    .discotheque,
    .soho,
    .rainbow,
    .luxury,
    .techno,
    .gamer,
    .cozy,
    .coastal,
    .japandi,
    .cottagecore,
    .skiChalet,
    .gothic,
    .creepy,
    .medieval,
    .eighties,
    .cartoon,
    .wood,
    .chocolate,
    .italianate,
    .brutalist,
    .artDeco,
    .chinese,
    .japanese,
    .cottage,
    .spanish,
    .morocco,
    .midcentury,
    .middleEastern,
    .farmhouse,
    .french,
    .christmas,
    .industrial,
    .scandinavian,
    .noStyle,
    .zen,
    .halloween,
    .concrete,
    .retro,
    .beachHouse,
    .isle,
    .stValentinesDay,
  ]

}

public enum HomedecorColorPalette: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case millennialGray // = 1
  case terracottaMirage // = 2
  case neonSunset // = 3
  case forestHues // = 4
  case peachOrchard // = 5
  case fuschiaBlossom // = 6
  case emeraldGem // = 7
  case pastelBreeze // = 8
  case azureMirage // = 9
  case twilightBlues // = 10
  case earthyHarmony // = 11
  case arcticLavender // = 12
  case antiqueSage // = 13
  case earthyHues // = 14
  case velvetDusk // = 15
  case oceanMist // = 16
  case amethystDream // = 17
  case sakuraBloom // = 18
  case lilacLove // = 19
  case whimsicalWish // = 20
  case turquoiseLagoon // = 21
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .millennialGray
    case 2: self = .terracottaMirage
    case 3: self = .neonSunset
    case 4: self = .forestHues
    case 5: self = .peachOrchard
    case 6: self = .fuschiaBlossom
    case 7: self = .emeraldGem
    case 8: self = .pastelBreeze
    case 9: self = .azureMirage
    case 10: self = .twilightBlues
    case 11: self = .earthyHarmony
    case 12: self = .arcticLavender
    case 13: self = .antiqueSage
    case 14: self = .earthyHues
    case 15: self = .velvetDusk
    case 16: self = .oceanMist
    case 17: self = .amethystDream
    case 18: self = .sakuraBloom
    case 19: self = .lilacLove
    case 20: self = .whimsicalWish
    case 21: self = .turquoiseLagoon
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .millennialGray: return 1
    case .terracottaMirage: return 2
    case .neonSunset: return 3
    case .forestHues: return 4
    case .peachOrchard: return 5
    case .fuschiaBlossom: return 6
    case .emeraldGem: return 7
    case .pastelBreeze: return 8
    case .azureMirage: return 9
    case .twilightBlues: return 10
    case .earthyHarmony: return 11
    case .arcticLavender: return 12
    case .antiqueSage: return 13
    case .earthyHues: return 14
    case .velvetDusk: return 15
    case .oceanMist: return 16
    case .amethystDream: return 17
    case .sakuraBloom: return 18
    case .lilacLove: return 19
    case .whimsicalWish: return 20
    case .turquoiseLagoon: return 21
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [HomedecorColorPalette] = [
    .unspecified,
    .millennialGray,
    .terracottaMirage,
    .neonSunset,
    .forestHues,
    .peachOrchard,
    .fuschiaBlossom,
    .emeraldGem,
    .pastelBreeze,
    .azureMirage,
    .twilightBlues,
    .earthyHarmony,
    .arcticLavender,
    .antiqueSage,
    .earthyHues,
    .velvetDusk,
    .oceanMist,
    .amethystDream,
    .sakuraBloom,
    .lilacLove,
    .whimsicalWish,
    .turquoiseLagoon,
  ]

}

public enum HomedecorSurfaceType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case wall // = 1
  case ceiling // = 2
  case floorSurface // = 3
  case door // = 4
  case cabinet // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .wall
    case 2: self = .ceiling
    case 3: self = .floorSurface
    case 4: self = .door
    case 5: self = .cabinet
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .wall: return 1
    case .ceiling: return 2
    case .floorSurface: return 3
    case .door: return 4
    case .cabinet: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [HomedecorSurfaceType] = [
    .unspecified,
    .wall,
    .ceiling,
    .floorSurface,
    .door,
    .cabinet,
  ]

}

/// All possible fields for generate action.
/// Providers use a subset; unused fields are ignored.
/// Plugins map enum values to provider-specific API strings.
public struct HomedecorGenerateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var file: String = String()

  public var roomStyle: HomedecorRoomStyle = .unspecified

  public var roomType: HomedecorRoomType = .unspecified

  public var processType: HomedecorProcessType = .unspecified

  public var styleSelection: HomedecorStyleSelection = .unspecified

  public var prompt: String = String()

  public var color: HomedecorColorPalette = .unspecified

  public var mask: String = String()

  public var surfaceType: HomedecorSurfaceType = .unspecified

  public var refImage: String = String()

  public var cacheDir: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Wrapped in task.Task.value as Any
public struct HomedecorGenerateResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: TypesImage {
    get {_result ?? TypesImage()}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  public var input: TypesImage {
    get {_input ?? TypesImage()}
    set {_input = newValue}
  }
  /// Returns true if `input` has been explicitly set.
  public var hasInput: Bool {self._input != nil}
  /// Clears the value of `input`. Subsequent reads from it will return its default value.
  public mutating func clearInput() {self._input = nil}

  public var roomStyle: HomedecorRoomStyle = .unspecified

  public var roomType: HomedecorRoomType = .unspecified

  public var processType: HomedecorProcessType = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _result: TypesImage? = nil
  fileprivate var _input: TypesImage? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.homedecor"

extension HomedecorProcessType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PROCESS_TYPE_UNSPECIFIED\0\u{1}INTERIOR\0\u{1}EXTERIOR\0\u{1}GARDEN\0\u{1}PAINT\0\u{1}REPLACE\0\u{1}FLOOR\0\u{1}REFERENCE\0\u{1}STAGING\0\u{1}DECLUTTER\0\u{1}FLOOR_PLAN\0\u{1}PLAN_TO_IMAGE\0")
}

extension HomedecorStyleSelection: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STYLE_SELECTION_UNSPECIFIED\0\u{1}STRUCTURAL_PRESERVATION\0\u{1}RENOVATION_DESIGN\0")
}

extension HomedecorRoomType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ROOM_TYPE_UNSPECIFIED\0\u{1}LIVING_ROOM\0\u{1}BEDROOM\0\u{1}KITCHEN\0\u{1}DINING_ROOM\0\u{1}BATHROOM\0\u{1}OFFICE\0\u{1}HOME_OFFICE\0\u{1}STUDY_ROOM\0\u{1}ATTIC\0\u{1}COFFEE_SHOP\0\u{1}GAMING_ROOM\0\u{1}RESTAURANT\0\u{1}TOILET\0\u{1}BALCONY\0\u{1}HALL\0\u{1}GARDEN_ROOM\0\u{1}DECK\0\u{1}APARTMENT\0\u{1}RESIDENTIAL\0\u{1}HOUSE\0\u{1}RETAIL\0\u{1}VILLA\0\u{1}UNDER_STAIR_SPACE\0\u{1}OFFICE_BUILDING\0\u{1}ENTRYWAY\0\u{1}LAUNDRY_ROOM\0\u{1}TOWER\0\u{1}RANCH\0\u{1}SWIMMING_POOL\0\u{1}YARD\0\u{1}OTHER_ROOM\0")
}

extension HomedecorRoomStyle: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ROOM_STYLE_UNSPECIFIED\0\u{1}MODERN\0\u{1}TROPICAL\0\u{1}MINIMALIST\0\u{1}BOHEMIAN\0\u{1}RUSTIC\0\u{1}VINTAGE\0\u{1}BAROQUE\0\u{1}MEDITERRANEAN\0\u{1}CYBERPUNK\0\u{1}BIOPHILIC\0\u{1}ANCIENT_EGYPTIAN\0\u{1}AIRBNB\0\u{1}DISCOTHEQUE\0\u{1}SOHO\0\u{1}RAINBOW\0\u{1}LUXURY\0\u{1}TECHNO\0\u{1}GAMER\0\u{1}COZY\0\u{1}COASTAL\0\u{1}JAPANDI\0\u{1}COTTAGECORE\0\u{1}SKI_CHALET\0\u{1}GOTHIC\0\u{1}CREEPY\0\u{1}MEDIEVAL\0\u{1}EIGHTIES\0\u{1}CARTOON\0\u{1}WOOD\0\u{1}CHOCOLATE\0\u{1}ITALIANATE\0\u{1}BRUTALIST\0\u{1}ART_DECO\0\u{1}CHINESE\0\u{1}JAPANESE\0\u{1}COTTAGE\0\u{1}SPANISH\0\u{1}MOROCCO\0\u{1}MIDCENTURY\0\u{1}MIDDLE_EASTERN\0\u{1}FARMHOUSE\0\u{1}FRENCH\0\u{1}CHRISTMAS\0\u{1}INDUSTRIAL\0\u{1}SCANDINAVIAN\0\u{1}NO_STYLE\0\u{1}ZEN\0\u{1}HALLOWEEN\0\u{1}CONCRETE\0\u{1}RETRO\0\u{1}BEACH_HOUSE\0\u{1}ISLE\0\u{1}ST_VALENTINES_DAY\0")
}

extension HomedecorColorPalette: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COLOR_PALETTE_UNSPECIFIED\0\u{1}MILLENNIAL_GRAY\0\u{1}TERRACOTTA_MIRAGE\0\u{1}NEON_SUNSET\0\u{1}FOREST_HUES\0\u{1}PEACH_ORCHARD\0\u{1}FUSCHIA_BLOSSOM\0\u{1}EMERALD_GEM\0\u{1}PASTEL_BREEZE\0\u{1}AZURE_MIRAGE\0\u{1}TWILIGHT_BLUES\0\u{1}EARTHY_HARMONY\0\u{1}ARCTIC_LAVENDER\0\u{1}ANTIQUE_SAGE\0\u{1}EARTHY_HUES\0\u{1}VELVET_DUSK\0\u{1}OCEAN_MIST\0\u{1}AMETHYST_DREAM\0\u{1}SAKURA_BLOOM\0\u{1}LILAC_LOVE\0\u{1}WHIMSICAL_WISH\0\u{1}TURQUOISE_LAGOON\0")
}

extension HomedecorSurfaceType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SURFACE_TYPE_UNSPECIFIED\0\u{1}WALL\0\u{1}CEILING\0\u{1}FLOOR_SURFACE\0\u{1}DOOR\0\u{1}CABINET\0")
}

extension HomedecorGenerateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenerateRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}file\0\u{3}room_style\0\u{3}room_type\0\u{3}process_type\0\u{3}style_selection\0\u{1}prompt\0\u{1}color\0\u{1}mask\0\u{3}surface_type\0\u{3}ref_image\0\u{3}cache_dir\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.file) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.roomStyle) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.roomType) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.processType) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.styleSelection) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.prompt) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.color) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.mask) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self.surfaceType) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.refImage) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.cacheDir) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.file.isEmpty {
      try visitor.visitSingularStringField(value: self.file, fieldNumber: 1)
    }
    if self.roomStyle != .unspecified {
      try visitor.visitSingularEnumField(value: self.roomStyle, fieldNumber: 2)
    }
    if self.roomType != .unspecified {
      try visitor.visitSingularEnumField(value: self.roomType, fieldNumber: 3)
    }
    if self.processType != .unspecified {
      try visitor.visitSingularEnumField(value: self.processType, fieldNumber: 4)
    }
    if self.styleSelection != .unspecified {
      try visitor.visitSingularEnumField(value: self.styleSelection, fieldNumber: 5)
    }
    if !self.prompt.isEmpty {
      try visitor.visitSingularStringField(value: self.prompt, fieldNumber: 6)
    }
    if self.color != .unspecified {
      try visitor.visitSingularEnumField(value: self.color, fieldNumber: 7)
    }
    if !self.mask.isEmpty {
      try visitor.visitSingularStringField(value: self.mask, fieldNumber: 8)
    }
    if self.surfaceType != .unspecified {
      try visitor.visitSingularEnumField(value: self.surfaceType, fieldNumber: 9)
    }
    if !self.refImage.isEmpty {
      try visitor.visitSingularStringField(value: self.refImage, fieldNumber: 10)
    }
    if !self.cacheDir.isEmpty {
      try visitor.visitSingularStringField(value: self.cacheDir, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: HomedecorGenerateRequest, rhs: HomedecorGenerateRequest) -> Bool {
    if lhs.file != rhs.file {return false}
    if lhs.roomStyle != rhs.roomStyle {return false}
    if lhs.roomType != rhs.roomType {return false}
    if lhs.processType != rhs.processType {return false}
    if lhs.styleSelection != rhs.styleSelection {return false}
    if lhs.prompt != rhs.prompt {return false}
    if lhs.color != rhs.color {return false}
    if lhs.mask != rhs.mask {return false}
    if lhs.surfaceType != rhs.surfaceType {return false}
    if lhs.refImage != rhs.refImage {return false}
    if lhs.cacheDir != rhs.cacheDir {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension HomedecorGenerateResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenerateResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{1}input\0\u{3}room_style\0\u{3}room_type\0\u{3}process_type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._input) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.roomStyle) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.roomType) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.processType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._input {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.roomStyle != .unspecified {
      try visitor.visitSingularEnumField(value: self.roomStyle, fieldNumber: 3)
    }
    if self.roomType != .unspecified {
      try visitor.visitSingularEnumField(value: self.roomType, fieldNumber: 4)
    }
    if self.processType != .unspecified {
      try visitor.visitSingularEnumField(value: self.processType, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: HomedecorGenerateResult, rhs: HomedecorGenerateResult) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._input != rhs._input {return false}
    if lhs.roomStyle != rhs.roomStyle {return false}
    if lhs.roomType != rhs.roomType {return false}
    if lhs.processType != rhs.processType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
