// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: news.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Wire types for the backend `/mobile/news` route — the category-
// agnostic news feed. The wasm news module proxies every request to
// the backend `/serverless/mobile/news` endpoint and deserializes the
// JSON response directly into these proto-generated Rust types, so
// the field names/order/types mirror the backend
// `crates/news-core::{NewsRequest, NewsResponse}` exactly.
//
// The proto is intentionally agnostic: nothing here is soccer- or
// health-specific. Category-specific overlays (in-review, national,
// FIFA, rollup snapshots for soccer; tag enrichment for health) all
// happen server-side; what arrives on the wire is a flat row stream
// plus the closed tag vocabulary for the requested category.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Vertical the news feed is sourced from. Serialized on the wire as
/// the lowercase token so the backend's `NewsRequest.category: String`
/// deserializes one-to-one with no custom mapping. New verticals are
/// added here as new enum values; the Rust task layer just forwards
/// the value through to the backend.
public enum NewsNewsCategory: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case soccer // = 1
  case health // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .soccer
    case 2: self = .health
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .soccer: return 1
    case .health: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [NewsNewsCategory] = [
    .unspecified,
    .soccer,
    .health,
  ]

}

/// Sort mode forwarded as the request body's `sort` string. Backend
/// (`crates/news-core::NewsRequest.sort`) accepts `"recent"` (default;
/// published_at DESC) and `"trending"` (trailing-7-day shortlink
/// resolves DESC). The trending sort is ignored server-side when `q` is
/// set — the FTS path stays chronological.
public enum NewsNewsSort: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case recent // = 1
  case trending // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .recent
    case 2: self = .trending
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .recent: return 1
    case .trending: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [NewsNewsSort] = [
    .unspecified,
    .recent,
    .trending,
  ]

}

/// One article row returned by `/mobile/news`. Field shape verified
/// 2026-06-25 against the live `staging.snapai.app/serverless/mobile/
/// news` endpoint — every typed field below is present in the actual
/// JSON. Per-row tag assignment lives inside `metadata.tags`, NOT at
/// row level; soccer rows carry `metadata.competition_ids` and
/// `metadata.team_ids`.
public struct NewsNewsItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Ingester-supplied article slug. Stable across re-crawls and
  /// safe to use as a list-row identity.
  public var id: String = String()

  /// Headline as published by the source. Already HTML-decoded by
  /// the ingester.
  public var title: String = String()

  /// Backend shortlink URL (`/serverless/mobile/s/<hash>`), NOT the
  /// source's raw permalink. Decoded by the backend redirect.
  public var url: String = String()

  /// Lead image URL. Empty when the article has no image; renderers
  /// should fall back to a category placeholder.
  public var imageURL: String = String()

  /// Source slug (e.g. `"football365"`, `"runners-world"`) — the
  /// ingester's normalized identifier, not a display name.
  public var source: String = String()

  /// Byline / author string. Empty when the article didn't expose
  /// one or the ingester couldn't parse it.
  public var author: String = String()

  /// Publication time as RFC 3339 UTC (e.g.
  /// `"2026-06-25T07:40:40Z"`). Parsed in Swift via the standard ISO
  /// formatter; opaque to Rust except for sort comparisons.
  public var publishedAt: String = String()

  /// Category slug echoed from the request (`"soccer"` /
  /// `"health"`). Useful for /mobile/news cross-category endpoints
  /// where the response mixes verticals.
  public var category: String = String()

  /// Read count (engagement metric). Increments server-side; 0 on a
  /// freshly-ingested row.
  public var hits: Int64 = 0

  /// Per-row enrichment payload — `mobile.news.metadata` JSONB
  /// dumped verbatim. Known keys: `importance` (i32, 0=normal,
  /// higher=featured), `summary` (string, may be empty), `tags`
  /// (string[], present for categories with a closed vocabulary like
  /// health), `competition_ids` / `team_ids` (string[], soccer
  /// only). Renderers cherry-pick what they need.
  public var metadata: SwiftProtobuf.Google_Protobuf_Struct {
    get {_metadata ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _metadata: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

public struct NewsNewsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Vertical to fetch. Required — the backend rejects an empty
  /// category with HTTP 400.
  public var category: NewsNewsCategory = .unspecified

  /// Page size. Server clamps to [1, 100]; default 30 when unset.
  public var limit: Int64 {
    get {_limit ?? 0}
    set {_limit = newValue}
  }
  /// Returns true if `limit` has been explicitly set.
  public var hasLimit: Bool {self._limit != nil}
  /// Clears the value of `limit`. Subsequent reads from it will return its default value.
  public mutating func clearLimit() {self._limit = nil}

  /// Offset-based cursor. Callers paginate by tracking
  /// `offset + items.len()` and stopping when the row count drops
  /// below `limit` (the backend's `next_offset` is collapsed away).
  public var offset: Int64 {
    get {_offset ?? 0}
    set {_offset = newValue}
  }
  /// Returns true if `offset` has been explicitly set.
  public var hasOffset: Bool {self._offset != nil}
  /// Clears the value of `offset`. Subsequent reads from it will return its default value.
  public mutating func clearOffset() {self._offset = nil}

  /// Full-text filter — postgres `plainto_tsquery`. Server caps
  /// length at 200 chars; empty/whitespace is ignored.
  public var q: String {
    get {_q ?? String()}
    set {_q = newValue}
  }
  /// Returns true if `q` has been explicitly set.
  public var hasQ: Bool {self._q != nil}
  /// Clears the value of `q`. Subsequent reads from it will return its default value.
  public mutating func clearQ() {self._q = nil}

  /// OR-match against the row's tag set. Values must come from the
  /// category's vocabulary (see `NewsResponse.tags_vocabulary`);
  /// unknown values match no rows.
  public var tags: [String] = []

  /// Sort mode. `UNSPECIFIED` (default) → backend default (`recent`).
  /// `TRENDING` re-orders by trailing-7-day shortlink resolves; the
  /// backend silently falls back to chronological when `q` is set, so
  /// this field has no effect during a search.
  public var sort: NewsNewsSort = .unspecified

  /// Category-specific filter params, forwarded to the backend request
  /// body verbatim. Lets each vertical surface its own narrowing knobs
  /// without growing the proto per-category:
  ///   • soccer  → `competition_id`, `team_id` (string ids; the backend
  ///     accepts numeric strings or raw ints)
  ///   • future  → whatever the vertical's `/mobile/news` overlay reads
  /// Unknown keys for a category are ignored by the backend. Empty map
  /// = no extra filters. Keys MUST be the snake_case wire names the
  /// backend expects (matches `crates/news-core::NewsRequest` field
  /// names), not the Swift/proto camelCase form.
  public var params: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _limit: Int64? = nil
  fileprivate var _offset: Int64? = nil
  fileprivate var _q: String? = nil
}

/// `/mobile/news` response. Field set verified 2026-06-25 against
/// the live `staging.snapai.app/serverless/mobile/news` endpoint.
public struct NewsNewsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Articles in published-at-DESC order, after any server-side
  /// category-specific overlays have been applied.
  public var items: [NewsNewsItem] = []

  /// Next offset to pass back as the request's `offset` for
  /// pagination. `items.len()` < requested `limit` is the canonical
  /// end-of-feed signal; callers don't strictly need this cursor
  /// but it short-circuits one extra round-trip when the count
  /// equals the limit.
  public var nextOffset: Int64 = 0

  /// Closed tag vocabulary for the requested category. Empty list
  /// for categories without a taxonomy (e.g. soccer); for health,
  /// the 16-element `HEALTH_TAGS` set: calories, nutrition,
  /// weight-loss, diet, blood-pressure, heart-rate, cardiovascular,
  /// diabetes, blood-sugar, exercise, fitness, sleep, hydration,
  /// mental-health, stress, general-wellness. Wire key is `tags`,
  /// NOT `tags_vocabulary`.
  public var tags: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.news"

extension NewsNewsCategory: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NEWS_CATEGORY_UNSPECIFIED\0\u{1}NEWS_CATEGORY_SOCCER\0\u{1}NEWS_CATEGORY_HEALTH\0")
}

extension NewsNewsSort: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NEWS_SORT_UNSPECIFIED\0\u{1}NEWS_SORT_RECENT\0\u{1}NEWS_SORT_TRENDING\0")
}

extension NewsNewsItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NewsItem"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}title\0\u{1}url\0\u{3}image_url\0\u{1}source\0\u{1}author\0\u{3}published_at\0\u{1}category\0\u{1}hits\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.imageURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.source) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.publishedAt) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.category) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.hits) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.imageURL.isEmpty {
      try visitor.visitSingularStringField(value: self.imageURL, fieldNumber: 4)
    }
    if !self.source.isEmpty {
      try visitor.visitSingularStringField(value: self.source, fieldNumber: 5)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 6)
    }
    if !self.publishedAt.isEmpty {
      try visitor.visitSingularStringField(value: self.publishedAt, fieldNumber: 7)
    }
    if !self.category.isEmpty {
      try visitor.visitSingularStringField(value: self.category, fieldNumber: 8)
    }
    if self.hits != 0 {
      try visitor.visitSingularInt64Field(value: self.hits, fieldNumber: 9)
    }
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NewsNewsItem, rhs: NewsNewsItem) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.url != rhs.url {return false}
    if lhs.imageURL != rhs.imageURL {return false}
    if lhs.source != rhs.source {return false}
    if lhs.author != rhs.author {return false}
    if lhs.publishedAt != rhs.publishedAt {return false}
    if lhs.category != rhs.category {return false}
    if lhs.hits != rhs.hits {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension NewsNewsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NewsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}category\0\u{1}limit\0\u{1}offset\0\u{1}q\0\u{1}tags\0\u{1}sort\0\u{1}params\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.category) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self._limit) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._offset) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._q) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.sort) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.params) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.category != .unspecified {
      try visitor.visitSingularEnumField(value: self.category, fieldNumber: 1)
    }
    try { if let v = self._limit {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._offset {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._q {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 5)
    }
    if self.sort != .unspecified {
      try visitor.visitSingularEnumField(value: self.sort, fieldNumber: 6)
    }
    if !self.params.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.params, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NewsNewsRequest, rhs: NewsNewsRequest) -> Bool {
    if lhs.category != rhs.category {return false}
    if lhs._limit != rhs._limit {return false}
    if lhs._offset != rhs._offset {return false}
    if lhs._q != rhs._q {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.sort != rhs.sort {return false}
    if lhs.params != rhs.params {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension NewsNewsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NewsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}items\0\u{3}next_offset\0\u{1}tags\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.nextOffset) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
    }
    if self.nextOffset != 0 {
      try visitor.visitSingularInt64Field(value: self.nextOffset, fieldNumber: 2)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NewsNewsResponse, rhs: NewsNewsResponse) -> Bool {
    if lhs.items != rhs.items {return false}
    if lhs.nextOffset != rhs.nextOffset {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
