// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: visual.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VisualPhotoSearchResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var total: Int32 = 0

  public var totalPages: Int32 = 0

  public var results: [VisualPhoto] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VisualPhoto: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var description_p: String {
    get {_storage._description_p ?? String()}
    set {_uniqueStorage()._description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {_storage._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {_uniqueStorage()._description_p = nil}

  public var altDescription: String {
    get {_storage._altDescription ?? String()}
    set {_uniqueStorage()._altDescription = newValue}
  }
  /// Returns true if `altDescription` has been explicitly set.
  public var hasAltDescription: Bool {_storage._altDescription != nil}
  /// Clears the value of `altDescription`. Subsequent reads from it will return its default value.
  public mutating func clearAltDescription() {_uniqueStorage()._altDescription = nil}

  public var width: Int32 {
    get {_storage._width}
    set {_uniqueStorage()._width = newValue}
  }

  public var height: Int32 {
    get {_storage._height}
    set {_uniqueStorage()._height = newValue}
  }

  public var color: String {
    get {_storage._color ?? String()}
    set {_uniqueStorage()._color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  public var hasColor: Bool {_storage._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  public mutating func clearColor() {_uniqueStorage()._color = nil}

  public var blurHash: String {
    get {_storage._blurHash ?? String()}
    set {_uniqueStorage()._blurHash = newValue}
  }
  /// Returns true if `blurHash` has been explicitly set.
  public var hasBlurHash: Bool {_storage._blurHash != nil}
  /// Clears the value of `blurHash`. Subsequent reads from it will return its default value.
  public mutating func clearBlurHash() {_uniqueStorage()._blurHash = nil}

  public var urls: VisualPhotoUrls {
    get {_storage._urls ?? VisualPhotoUrls()}
    set {_uniqueStorage()._urls = newValue}
  }
  /// Returns true if `urls` has been explicitly set.
  public var hasUrls: Bool {_storage._urls != nil}
  /// Clears the value of `urls`. Subsequent reads from it will return its default value.
  public mutating func clearUrls() {_uniqueStorage()._urls = nil}

  public var user: VisualPhotoUser {
    get {_storage._user ?? VisualPhotoUser()}
    set {_uniqueStorage()._user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  public var hasUser: Bool {_storage._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  public mutating func clearUser() {_uniqueStorage()._user = nil}

  public var links: VisualPhotoLinks {
    get {_storage._links ?? VisualPhotoLinks()}
    set {_uniqueStorage()._links = newValue}
  }
  /// Returns true if `links` has been explicitly set.
  public var hasLinks: Bool {_storage._links != nil}
  /// Clears the value of `links`. Subsequent reads from it will return its default value.
  public mutating func clearLinks() {_uniqueStorage()._links = nil}

  public var likes: Int32 {
    get {_storage._likes}
    set {_uniqueStorage()._likes = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct VisualPhotoUrls: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var raw: String = String()

  public var full: String = String()

  public var regular: String = String()

  public var small: String = String()

  public var thumb: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VisualPhotoUser: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var username: String = String()

  public var name: String = String()

  public var profileImage: String {
    get {_profileImage ?? String()}
    set {_profileImage = newValue}
  }
  /// Returns true if `profileImage` has been explicitly set.
  public var hasProfileImage: Bool {self._profileImage != nil}
  /// Clears the value of `profileImage`. Subsequent reads from it will return its default value.
  public mutating func clearProfileImage() {self._profileImage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _profileImage: String? = nil
}

public struct VisualPhotoLinks: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var html: String {
    get {_html ?? String()}
    set {_html = newValue}
  }
  /// Returns true if `html` has been explicitly set.
  public var hasHtml: Bool {self._html != nil}
  /// Clears the value of `html`. Subsequent reads from it will return its default value.
  public mutating func clearHtml() {self._html = nil}

  public var download: String {
    get {_download ?? String()}
    set {_download = newValue}
  }
  /// Returns true if `download` has been explicitly set.
  public var hasDownload: Bool {self._download != nil}
  /// Clears the value of `download`. Subsequent reads from it will return its default value.
  public mutating func clearDownload() {self._download = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _html: String? = nil
  fileprivate var _download: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.visual"

extension VisualPhotoSearchResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhotoSearchResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}total\0\u{1}total_pages\0\u{1}results\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.total) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.totalPages) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.total != 0 {
      try visitor.visitSingularInt32Field(value: self.total, fieldNumber: 1)
    }
    if self.totalPages != 0 {
      try visitor.visitSingularInt32Field(value: self.totalPages, fieldNumber: 2)
    }
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisualPhotoSearchResult, rhs: VisualPhotoSearchResult) -> Bool {
    if lhs.total != rhs.total {return false}
    if lhs.totalPages != rhs.totalPages {return false}
    if lhs.results != rhs.results {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisualPhoto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Photo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}description\0\u{1}alt_description\0\u{1}width\0\u{1}height\0\u{1}color\0\u{1}blur_hash\0\u{1}urls\0\u{1}user\0\u{1}links\0\u{1}likes\0")

  fileprivate class _StorageClass {
    var _id: String = String()
    var _description_p: String? = nil
    var _altDescription: String? = nil
    var _width: Int32 = 0
    var _height: Int32 = 0
    var _color: String? = nil
    var _blurHash: String? = nil
    var _urls: VisualPhotoUrls? = nil
    var _user: VisualPhotoUser? = nil
    var _links: VisualPhotoLinks? = nil
    var _likes: Int32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _description_p = source._description_p
      _altDescription = source._altDescription
      _width = source._width
      _height = source._height
      _color = source._color
      _blurHash = source._blurHash
      _urls = source._urls
      _user = source._user
      _links = source._links
      _likes = source._likes
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._altDescription) }()
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._width) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._height) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._color) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._blurHash) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._urls) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._user) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._links) }()
        case 11: try { try decoder.decodeSingularInt32Field(value: &_storage._likes) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      try { if let v = _storage._description_p {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._altDescription {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      if _storage._width != 0 {
        try visitor.visitSingularInt32Field(value: _storage._width, fieldNumber: 4)
      }
      if _storage._height != 0 {
        try visitor.visitSingularInt32Field(value: _storage._height, fieldNumber: 5)
      }
      try { if let v = _storage._color {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._blurHash {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._urls {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._user {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._links {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if _storage._likes != 0 {
        try visitor.visitSingularInt32Field(value: _storage._likes, fieldNumber: 11)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisualPhoto, rhs: VisualPhoto) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._altDescription != rhs_storage._altDescription {return false}
        if _storage._width != rhs_storage._width {return false}
        if _storage._height != rhs_storage._height {return false}
        if _storage._color != rhs_storage._color {return false}
        if _storage._blurHash != rhs_storage._blurHash {return false}
        if _storage._urls != rhs_storage._urls {return false}
        if _storage._user != rhs_storage._user {return false}
        if _storage._links != rhs_storage._links {return false}
        if _storage._likes != rhs_storage._likes {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisualPhotoUrls: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhotoUrls"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}raw\0\u{1}full\0\u{1}regular\0\u{1}small\0\u{1}thumb\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.raw) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.full) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.regular) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.small) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.thumb) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.raw.isEmpty {
      try visitor.visitSingularStringField(value: self.raw, fieldNumber: 1)
    }
    if !self.full.isEmpty {
      try visitor.visitSingularStringField(value: self.full, fieldNumber: 2)
    }
    if !self.regular.isEmpty {
      try visitor.visitSingularStringField(value: self.regular, fieldNumber: 3)
    }
    if !self.small.isEmpty {
      try visitor.visitSingularStringField(value: self.small, fieldNumber: 4)
    }
    if !self.thumb.isEmpty {
      try visitor.visitSingularStringField(value: self.thumb, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisualPhotoUrls, rhs: VisualPhotoUrls) -> Bool {
    if lhs.raw != rhs.raw {return false}
    if lhs.full != rhs.full {return false}
    if lhs.regular != rhs.regular {return false}
    if lhs.small != rhs.small {return false}
    if lhs.thumb != rhs.thumb {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisualPhotoUser: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhotoUser"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}username\0\u{1}name\0\u{1}profile_image\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.username) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._profileImage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.username.isEmpty {
      try visitor.visitSingularStringField(value: self.username, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try { if let v = self._profileImage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisualPhotoUser, rhs: VisualPhotoUser) -> Bool {
    if lhs.username != rhs.username {return false}
    if lhs.name != rhs.name {return false}
    if lhs._profileImage != rhs._profileImage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisualPhotoLinks: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhotoLinks"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}html\0\u{1}download\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._html) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._download) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._html {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._download {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisualPhotoLinks, rhs: VisualPhotoLinks) -> Bool {
    if lhs._html != rhs._html {return false}
    if lhs._download != rhs._download {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
