// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: smartcar.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Wire types for the connected-car ("smartcar") domain. The wasm
// smartcar module proxies every request to the vehicle backend and
// hands the JSON responses back to the app.
//
// Auth model: the app completes a provider-hosted Connect flow in native code.
// Native code owns only the WebView shell; the guest observes hosted page
// URLs/body text, detects provider-specific completion, caches the resulting
// credential, and injects it into every subsequent read/control request.
//
// The proto is provider-agnostic: it models the shape of the calls,
// not any one backend. Two read families exist because the backend
// splits its own routes that way — a universal set that works for any
// connected vehicle, and a vendor-scoped set (path prefix `tesla`)
// that only applies to vehicles from one OEM. Callers pick the family
// the connected vehicle supports.
//
// Read responses are modeled after the Smartcar API reference's
// normalized schema (the full superset). The default backend returns a
// SUBSET of those fields, so every telemetry field is `optional` and the
// guest populates only what a given endpoint reports — unset ≠ zero.
// Control responses stay minimal (the echoed action) since the backend
// only echoes what it applied.

import SwiftProtobuf
#if canImport(FlowKit)
import FlowKit
#else
import WasmSwiftProtobuf
#endif

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Charge session toggle. Despite the endpoint name it is a binary
/// start/stop of charging, not a numeric limit.
public enum SmartcarChargeAction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case start // = 1
  case stop // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .start
    case 2: self = .stop
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .start: return 1
    case .stop: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarChargeAction] = [
    .unspecified,
    .start,
    .stop,
  ]

}

/// Cabin climate (HVAC) command. `START`/`STOP` turn conditioning on/off;
/// `SET` applies the accompanying `temperature_celsius` target.
public enum SmartcarClimateAction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case start // = 1
  case stop // = 2
  case set // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .start
    case 2: self = .stop
    case 3: self = .set
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .start: return 1
    case .stop: return 2
    case .set: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarClimateAction] = [
    .unspecified,
    .start,
    .stop,
    .set,
  ]

}

/// Front defroster command — open (on) or close (off).
public enum SmartcarDefrosterAction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case `open` // = 1
  case close // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .open
    case 2: self = .close
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .open: return 1
    case .close: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarDefrosterAction] = [
    .unspecified,
    .open,
    .close,
  ]

}

/// Steering-wheel heater toggle — binary on/off (no level).
public enum SmartcarHeaterAction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case start // = 1
  case stop // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .start
    case 2: self = .stop
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .start: return 1
    case .stop: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarHeaterAction] = [
    .unspecified,
    .start,
    .stop,
  ]

}

/// Lock or unlock the vehicle.
public enum SmartcarSecurityAction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case lock // = 1
  case unlock // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .lock
    case 2: self = .unlock
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .lock: return 1
    case .unlock: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarSecurityAction] = [
    .unspecified,
    .lock,
    .unlock,
  ]

}

/// Smartcar Connect launch mode. `LIVE` hits real OEM auth; `TEST` uses
/// Smartcar's test credentials; `SIMULATED` uses a simulated vehicle. The
/// guest chooses the mode per build/provider so the app doesn't decide.
public enum SmartcarConnectMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case live // = 1
  case test // = 2
  case simulated // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .live
    case 2: self = .test
    case 3: self = .simulated
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .live: return 1
    case .test: return 2
    case .simulated: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarConnectMode] = [
    .unspecified,
    .live,
    .test,
    .simulated,
  ]

}

/// Guest decision for one native WebView observation. The app owns only the
/// WebView shell; provider-specific terminal URLs/body parsing live in the
/// guest.
public enum SmartcarHostedConnectAction: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case `continue` // = 0
  case cancel // = 1
  case complete // = 2
  case error // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .continue
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .continue
    case 1: self = .cancel
    case 2: self = .complete
    case 3: self = .error
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .continue: return 0
    case .cancel: return 1
    case .complete: return 2
    case .error: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SmartcarHostedConnectAction] = [
    .continue,
    .cancel,
    .complete,
    .error,
  ]

}

/// Request for `ConnectConfig`. The caller passes the mode it wants to
/// run Connect in (an app/build concern — test vs live); the guest
/// returns the matching credentials and the effective mode.
public struct SmartcarConnectConfigRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Desired launch mode. `UNSPECIFIED` lets the guest pick its default.
  public var mode: SmartcarConnectMode = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// OAuth Connect parameters the native app needs to launch the Connect
/// flow. Owned by the guest (per provider) so the app never hardcodes a
/// backend's client identity or scope surface; the app reads these and
/// opens `connect_url` in a WebView.
public struct SmartcarConnectConfigResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Smartcar application/client id used to launch Connect. Informational
  /// — already baked into `connect_url`.
  public var applicationID: String = String()

  /// Redirect URI registered for the provider's Smartcar app (a custom
  /// scheme like `sc<application_id>://exchange`). The app opens
  /// `connect_url` in a web view and intercepts navigation to this URI's
  /// scheme to capture the `code`. Smartcar only accepts a redirect whose
  /// scheme is registered for the app, so this is NOT rewritten.
  public var redirectUri: String = String()

  /// Full permission surface requested. Informational — already baked
  /// into `connect_url`.
  public var scope: [String] = []

  /// Effective launch mode (already reflected in `connect_url`).
  public var mode: SmartcarConnectMode = .unspecified

  /// Fully-built Smartcar Connect authorize URL to load in a web view.
  public var connectURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One observation from the native hosted-Connect WebView.
public struct SmartcarHostedConnectEventRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Current frame URL, if any.
  public var url: String = String()

  /// Main-frame body text, if available after navigation completes or from a
  /// JavaScript bridge message.
  public var bodyText: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Decision returned by the guest after parsing a hosted-Connect observation.
public struct SmartcarHostedConnectEventResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// What the native WebView should do next.
  public var action: SmartcarHostedConnectAction = .continue

  /// Provider credential cached by the guest on success. It is still named
  /// `user_id` to match the existing provider-agnostic Smartcar credential
  /// surface used by read/control calls.
  public var userID: String = String()

  /// Human-readable error when `action == ERROR`.
  public var error: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for cached Smartcar accounts for the provider. The guest reads
/// its local session cache only; no network call is made.
public struct SmartcarAccountsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Select one cached account as active. Reads/controls use the first cached
/// account, so switching means moving this `user_id` to the front of the local
/// cache array.
public struct SmartcarSwitchAccountRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Remove one cached account from the local Smartcar session cache. If the
/// deleted account is active, the next cached account becomes active.
public struct SmartcarDeleteAccountRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One locally cached connected account. `user_id` is the provider credential
/// surface name retained for compatibility; for Mustname it is the Smartcar
/// access token captured from hosted Connect.
public struct SmartcarAccount: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userID: String = String()

  public var label: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Locally cached accounts for this provider. The first account is the active
/// account used by reads/controls.
public struct SmartcarAccountList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accounts: [SmartcarAccount] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One connected vehicle from the account's garage.
public struct SmartcarVehicle: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Stable per-vehicle identifier used as `vehicle_id` in read/control
  /// requests.
  public var vehicleID: String = String()

  /// Manufacturer/brand string as reported by the backend (e.g.
  /// `"Tesla"`, `"Ford"`, or a demo label). May drive which read family
  /// the app uses.
  public var make: String = String()

  /// Model name as reported by the backend. May be empty.
  public var model: String = String()

  /// Model year as reported by the backend. May be empty.
  public var year: String = String()

  /// Any additional per-vehicle fields the backend returns, forwarded
  /// verbatim without a fixed schema.
  public var extra: SwiftProtobuf.Google_Protobuf_Struct {
    get {_extra ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_extra = newValue}
  }
  /// Returns true if `extra` has been explicitly set.
  public var hasExtra: Bool {self._extra != nil}
  /// Clears the value of `extra`. Subsequent reads from it will return its default value.
  public mutating func clearExtra() {self._extra = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _extra: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

/// Response of the "list all vehicles" call.
public struct SmartcarVehicleList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Every vehicle connected to the account. Empty when the account has
  /// completed auth but connected no vehicles.
  public var vehicles: [SmartcarVehicle] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Selects which connected vehicle a read/control targets. The
/// authorizing `user_id` is NOT on the wire here — the guest injects its
/// cached value.
public struct SmartcarReadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target vehicle. Take this from `VehicleList.vehicles[].vehicle_id`.
  /// Empty selects the account's currently-active vehicle backend-side.
  public var vehicleID: String = String()

  /// Vehicle make for brand-specific reads (for example Smartcar's
  /// `{make}/speedometer` endpoint). Use the selected `Vehicle.make` when
  /// available; the guest/provider normalizes casing for its backend.
  public var make: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One closure's open/close state, mirroring the Smartcar lock-status
/// standard's `{type, status}` objects (used for doors, windows, sunroof,
/// storage, and charging port).
public struct SmartcarClosureStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Closure location label as reported (e.g. `"frontLeft"`, `"rear"`).
  public var type: String = String()

  /// Closure state as reported: typically `"OPEN"`, `"CLOSED"`, or
  /// `"UNKNOWN"` (supported but no valid value).
  public var status: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// `Odometer` / `TeslaVehicleAttributes` read.
public struct SmartcarOdometer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Total distance traveled, in kilometers. Source: `distance`.
  public var distanceKm: Double {
    get {_distanceKm ?? 0}
    set {_distanceKm = newValue}
  }
  /// Returns true if `distanceKm` has been explicitly set.
  public var hasDistanceKm: Bool {self._distanceKm != nil}
  /// Clears the value of `distanceKm`. Subsequent reads from it will return its default value.
  public mutating func clearDistanceKm() {self._distanceKm = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _distanceKm: Double? = nil
}

/// EV battery level. `BatteryLevel` (universal) and `TeslaBatteryStatus`
/// (vendor-scoped) both map here.
public struct SmartcarBatteryLevel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// State of charge as a fraction in [0, 1]. Source: `percentRemaining`.
  public var percentRemaining: Double {
    get {_percentRemaining ?? 0}
    set {_percentRemaining = newValue}
  }
  /// Returns true if `percentRemaining` has been explicitly set.
  public var hasPercentRemaining: Bool {self._percentRemaining != nil}
  /// Clears the value of `percentRemaining`. Subsequent reads from it will return its default value.
  public mutating func clearPercentRemaining() {self._percentRemaining = nil}

  /// Estimated remaining driving range, in kilometers. Source: `range`.
  public var rangeKm: Double {
    get {_rangeKm ?? 0}
    set {_rangeKm = newValue}
  }
  /// Returns true if `rangeKm` has been explicitly set.
  public var hasRangeKm: Bool {self._rangeKm != nil}
  /// Clears the value of `rangeKm`. Subsequent reads from it will return its default value.
  public mutating func clearRangeKm() {self._rangeKm = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _percentRemaining: Double? = nil
  fileprivate var _rangeKm: Double? = nil
}

/// EV charge target. `ChargeLimit` read.
public struct SmartcarChargeLimit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Configured charge target as a fraction in [0, 1] (0.8 == 80%).
  /// Source: `limit`.
  public var limit: Double {
    get {_limit ?? 0}
    set {_limit = newValue}
  }
  /// Returns true if `limit` has been explicitly set.
  public var hasLimit: Bool {self._limit != nil}
  /// Clears the value of `limit`. Subsequent reads from it will return its default value.
  public mutating func clearLimit() {self._limit = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _limit: Double? = nil
}

/// EV charge status. `TeslaChargeStatus` read.
public struct SmartcarChargeStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Whether a charging cable is currently plugged in.
  /// Source: `isPluggedIn`.
  public var isPluggedIn: Bool {
    get {_isPluggedIn ?? false}
    set {_isPluggedIn = newValue}
  }
  /// Returns true if `isPluggedIn` has been explicitly set.
  public var hasIsPluggedIn: Bool {self._isPluggedIn != nil}
  /// Clears the value of `isPluggedIn`. Subsequent reads from it will return its default value.
  public mutating func clearIsPluggedIn() {self._isPluggedIn = nil}

  /// Charging state label: `CHARGING`, `FULLY_CHARGED`, `NOT_CHARGING`.
  /// Source: `state`.
  public var state: String {
    get {_state ?? String()}
    set {_state = newValue}
  }
  /// Returns true if `state` has been explicitly set.
  public var hasState: Bool {self._state != nil}
  /// Clears the value of `state`. Subsequent reads from it will return its default value.
  public mutating func clearState() {self._state = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _isPluggedIn: Bool? = nil
  fileprivate var _state: String? = nil
}

/// EV rated battery capacity. `NominalCapacity` read.
public struct SmartcarNominalCapacity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Rated (nominal) battery capacity, in kilowatt-hours.
  /// Source: `capacity`.
  public var capacityKwh: Double {
    get {_capacityKwh ?? 0}
    set {_capacityKwh = newValue}
  }
  /// Returns true if `capacityKwh` has been explicitly set.
  public var hasCapacityKwh: Bool {self._capacityKwh != nil}
  /// Clears the value of `capacityKwh`. Subsequent reads from it will return its default value.
  public mutating func clearCapacityKwh() {self._capacityKwh = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _capacityKwh: Double? = nil
}

/// Tire pressures, in kilopascals, by corner. `TiresPressure` read.
/// Sources: `frontLeft`, `frontRight`, `backLeft`, `backRight`.
public struct SmartcarTirePressure: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var frontLeftKpa: Double {
    get {_frontLeftKpa ?? 0}
    set {_frontLeftKpa = newValue}
  }
  /// Returns true if `frontLeftKpa` has been explicitly set.
  public var hasFrontLeftKpa: Bool {self._frontLeftKpa != nil}
  /// Clears the value of `frontLeftKpa`. Subsequent reads from it will return its default value.
  public mutating func clearFrontLeftKpa() {self._frontLeftKpa = nil}

  public var frontRightKpa: Double {
    get {_frontRightKpa ?? 0}
    set {_frontRightKpa = newValue}
  }
  /// Returns true if `frontRightKpa` has been explicitly set.
  public var hasFrontRightKpa: Bool {self._frontRightKpa != nil}
  /// Clears the value of `frontRightKpa`. Subsequent reads from it will return its default value.
  public mutating func clearFrontRightKpa() {self._frontRightKpa = nil}

  public var backLeftKpa: Double {
    get {_backLeftKpa ?? 0}
    set {_backLeftKpa = newValue}
  }
  /// Returns true if `backLeftKpa` has been explicitly set.
  public var hasBackLeftKpa: Bool {self._backLeftKpa != nil}
  /// Clears the value of `backLeftKpa`. Subsequent reads from it will return its default value.
  public mutating func clearBackLeftKpa() {self._backLeftKpa = nil}

  public var backRightKpa: Double {
    get {_backRightKpa ?? 0}
    set {_backRightKpa = newValue}
  }
  /// Returns true if `backRightKpa` has been explicitly set.
  public var hasBackRightKpa: Bool {self._backRightKpa != nil}
  /// Clears the value of `backRightKpa`. Subsequent reads from it will return its default value.
  public mutating func clearBackRightKpa() {self._backRightKpa = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _frontLeftKpa: Double? = nil
  fileprivate var _frontRightKpa: Double? = nil
  fileprivate var _backLeftKpa: Double? = nil
  fileprivate var _backRightKpa: Double? = nil
}

/// Lock status. `LockStatus` read. Mirrors the Smartcar standard's
/// structured closure arrays; the default backend may report only the
/// overall `is_locked` flag, leaving the arrays empty.
public struct SmartcarLockStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Whether the vehicle is locked overall. Source: `isLocked`.
  public var isLocked: Bool {
    get {_isLocked ?? false}
    set {_isLocked = newValue}
  }
  /// Returns true if `isLocked` has been explicitly set.
  public var hasIsLocked: Bool {self._isLocked != nil}
  /// Clears the value of `isLocked`. Subsequent reads from it will return its default value.
  public mutating func clearIsLocked() {self._isLocked = nil}

  public var doors: [SmartcarClosureStatus] = []

  public var windows: [SmartcarClosureStatus] = []

  public var sunroof: [SmartcarClosureStatus] = []

  public var storage: [SmartcarClosureStatus] = []

  public var chargingPort: [SmartcarClosureStatus] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _isLocked: Bool? = nil
}

/// Engine oil life. `OilLive` read.
public struct SmartcarEngineOil: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Remaining engine-oil life as a fraction in [0, 1] (1 == fresh,
  /// 0 == change now; ICE/hybrid only). Source: `lifeRemaining`.
  public var lifeRemaining: Double {
    get {_lifeRemaining ?? 0}
    set {_lifeRemaining = newValue}
  }
  /// Returns true if `lifeRemaining` has been explicitly set.
  public var hasLifeRemaining: Bool {self._lifeRemaining != nil}
  /// Clears the value of `lifeRemaining`. Subsequent reads from it will return its default value.
  public mutating func clearLifeRemaining() {self._lifeRemaining = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _lifeRemaining: Double? = nil
}

/// Granted scopes/permissions. `Permissions` read.
public struct SmartcarPermissions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scopes the backend reports as granted for this vehicle.
  public var permissions: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A single temperature reading, in degrees Celsius. Used by the
/// vendor-scoped `TeslaInteriorTemperature` / `TeslaExteriorTemperature`
/// reads. Vendor-scoped shape (no public standard); populated
/// best-effort.
public struct SmartcarTemperature: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var celsius: Double {
    get {_celsius ?? 0}
    set {_celsius = newValue}
  }
  /// Returns true if `celsius` has been explicitly set.
  public var hasCelsius: Bool {self._celsius != nil}
  /// Clears the value of `celsius`. Subsequent reads from it will return its default value.
  public mutating func clearCelsius() {self._celsius = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _celsius: Double? = nil
}

/// Current vehicle speed. `Speedometer` maps Smartcar's brand-specific
/// `{make}/speedometer` read. With Smartcar's default metric unit system,
/// source `speed` is kilometers per hour.
public struct SmartcarSpeedometer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var speedKph: Double {
    get {_speedKph ?? 0}
    set {_speedKph = newValue}
  }
  /// Returns true if `speedKph` has been explicitly set.
  public var hasSpeedKph: Bool {self._speedKph != nil}
  /// Clears the value of `speedKph`. Subsequent reads from it will return its default value.
  public mutating func clearSpeedKph() {self._speedKph = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _speedKph: Double? = nil
}

/// Request for `LookupVin`, the public VIN decoder. The caller supplies a
/// 17-character VIN; no connected-car account is required.
public struct SmartcarLookupVinRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var vin: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Cabin climate (HVAC) state. `TeslaGetCabinClimate` read. Vendor-scoped
/// shape; populated best-effort.
public struct SmartcarCabinClimate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Whether cabin climate is currently on.
  public var on: Bool {
    get {_on ?? false}
    set {_on = newValue}
  }
  /// Returns true if `on` has been explicitly set.
  public var hasOn: Bool {self._on != nil}
  /// Clears the value of `on`. Subsequent reads from it will return its default value.
  public mutating func clearOn() {self._on = nil}

  /// Current target temperature, in degrees Celsius.
  public var temperatureCelsius: Double {
    get {_temperatureCelsius ?? 0}
    set {_temperatureCelsius = newValue}
  }
  /// Returns true if `temperatureCelsius` has been explicitly set.
  public var hasTemperatureCelsius: Bool {self._temperatureCelsius != nil}
  /// Clears the value of `temperatureCelsius`. Subsequent reads from it will return its default value.
  public mutating func clearTemperatureCelsius() {self._temperatureCelsius = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _on: Bool? = nil
  fileprivate var _temperatureCelsius: Double? = nil
}

/// A vendor-scoped on/off accessory state. Used by `TeslaGetDefroster`
/// and `TeslaGetSteeringWheel`. Vendor-scoped shape; populated
/// best-effort.
public struct SmartcarToggleState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Whether the accessory (defroster / steering-wheel heater) is on.
  public var on: Bool {
    get {_on ?? false}
    set {_on = newValue}
  }
  /// Returns true if `on` has been explicitly set.
  public var hasOn: Bool {self._on != nil}
  /// Clears the value of `on`. Subsequent reads from it will return its default value.
  public mutating func clearOn() {self._on = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _on: Bool? = nil
}

/// Free-form vehicle status. `TeslaVehicleStatus` read. Vendor-scoped;
/// passed through as reported.
public struct SmartcarVehicleStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Status label as reported by the backend.
  public var status: String {
    get {_status ?? String()}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {self._status = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _status: String? = nil
}

/// Start/stop the charge session for a vehicle.
public struct SmartcarChargeControlRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target vehicle (see `ReadRequest.vehicle_id`).
  public var vehicleID: String = String()

  /// Charging toggle to apply.
  public var action: SmartcarChargeAction = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Set or toggle cabin climate (HVAC).
public struct SmartcarCabinClimateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target vehicle.
  public var vehicleID: String = String()

  /// Climate command. When `SET`, `temperature_celsius` is applied.
  public var action: SmartcarClimateAction = .unspecified

  /// Target cabin temperature in degrees Celsius. Used only when
  /// `action == SET`; ignored otherwise.
  public var temperatureCelsius: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Open/close the front defroster.
public struct SmartcarDefrosterRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target vehicle.
  public var vehicleID: String = String()

  /// Defroster command to apply.
  public var action: SmartcarDefrosterAction = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Toggle the steering-wheel heater.
public struct SmartcarSteeringWheelRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target vehicle.
  public var vehicleID: String = String()

  /// Heater toggle to apply.
  public var action: SmartcarHeaterAction = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Lock or unlock the vehicle.
public struct SmartcarSecurityRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Target vehicle.
  public var vehicleID: String = String()

  /// Security command to apply.
  public var action: SmartcarSecurityAction = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Result of a control command. The backend echoes the resulting
/// `action`, which the app can compare against the requested one to
/// confirm the transition.
public struct SmartcarControlResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Action the backend reports after applying the command (e.g.
  /// `"START"`, `"SET"`).
  public var action: String = String()

  /// Any additional fields the backend returned alongside `action`,
  /// forwarded verbatim.
  public var data: SwiftProtobuf.Google_Protobuf_Struct {
    get {_data ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_data = newValue}
  }
  /// Returns true if `data` has been explicitly set.
  public var hasData: Bool {self._data != nil}
  /// Clears the value of `data`. Subsequent reads from it will return its default value.
  public mutating func clearData() {self._data = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _data: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.smartcar"

extension SmartcarChargeAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CHARGE_ACTION_UNSPECIFIED\0\u{1}CHARGE_ACTION_START\0\u{1}CHARGE_ACTION_STOP\0")
}

extension SmartcarClimateAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CLIMATE_ACTION_UNSPECIFIED\0\u{1}CLIMATE_ACTION_START\0\u{1}CLIMATE_ACTION_STOP\0\u{1}CLIMATE_ACTION_SET\0")
}

extension SmartcarDefrosterAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEFROSTER_ACTION_UNSPECIFIED\0\u{1}DEFROSTER_ACTION_OPEN\0\u{1}DEFROSTER_ACTION_CLOSE\0")
}

extension SmartcarHeaterAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HEATER_ACTION_UNSPECIFIED\0\u{1}HEATER_ACTION_START\0\u{1}HEATER_ACTION_STOP\0")
}

extension SmartcarSecurityAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SECURITY_ACTION_UNSPECIFIED\0\u{1}SECURITY_ACTION_LOCK\0\u{1}SECURITY_ACTION_UNLOCK\0")
}

extension SmartcarConnectMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CONNECT_MODE_UNSPECIFIED\0\u{1}CONNECT_MODE_LIVE\0\u{1}CONNECT_MODE_TEST\0\u{1}CONNECT_MODE_SIMULATED\0")
}

extension SmartcarHostedConnectAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HOSTED_CONNECT_ACTION_CONTINUE\0\u{1}HOSTED_CONNECT_ACTION_CANCEL\0\u{1}HOSTED_CONNECT_ACTION_COMPLETE\0\u{1}HOSTED_CONNECT_ACTION_ERROR\0")
}

extension SmartcarConnectConfigRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectConfigRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarConnectConfigRequest, rhs: SmartcarConnectConfigRequest) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarConnectConfigResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectConfigResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}application_id\0\u{3}redirect_uri\0\u{1}scope\0\u{1}mode\0\u{3}connect_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.applicationID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.redirectUri) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.scope) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.connectURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.applicationID.isEmpty {
      try visitor.visitSingularStringField(value: self.applicationID, fieldNumber: 1)
    }
    if !self.redirectUri.isEmpty {
      try visitor.visitSingularStringField(value: self.redirectUri, fieldNumber: 2)
    }
    if !self.scope.isEmpty {
      try visitor.visitRepeatedStringField(value: self.scope, fieldNumber: 3)
    }
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 4)
    }
    if !self.connectURL.isEmpty {
      try visitor.visitSingularStringField(value: self.connectURL, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarConnectConfigResponse, rhs: SmartcarConnectConfigResponse) -> Bool {
    if lhs.applicationID != rhs.applicationID {return false}
    if lhs.redirectUri != rhs.redirectUri {return false}
    if lhs.scope != rhs.scope {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.connectURL != rhs.connectURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarHostedConnectEventRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostedConnectEventRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0\u{3}body_text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.bodyText) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if !self.bodyText.isEmpty {
      try visitor.visitSingularStringField(value: self.bodyText, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarHostedConnectEventRequest, rhs: SmartcarHostedConnectEventRequest) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.bodyText != rhs.bodyText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarHostedConnectEventResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostedConnectEventResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}action\0\u{3}user_id\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.action != .continue {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 1)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 2)
    }
    if !self.error.isEmpty {
      try visitor.visitSingularStringField(value: self.error, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarHostedConnectEventResponse, rhs: SmartcarHostedConnectEventResponse) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.error != rhs.error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarAccountsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccountsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarAccountsRequest, rhs: SmartcarAccountsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarSwitchAccountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwitchAccountRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarSwitchAccountRequest, rhs: SmartcarSwitchAccountRequest) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarDeleteAccountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteAccountRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarDeleteAccountRequest, rhs: SmartcarDeleteAccountRequest) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarAccount: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Account"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0\u{1}label\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.label) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarAccount, rhs: SmartcarAccount) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.label != rhs.label {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarAccountList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccountList"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accounts\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.accounts) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.accounts.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.accounts, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarAccountList, rhs: SmartcarAccountList) -> Bool {
    if lhs.accounts != rhs.accounts {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarVehicle: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Vehicle"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}make\0\u{1}model\0\u{1}year\0\u{1}extra\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.make) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.year) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._extra) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if !self.make.isEmpty {
      try visitor.visitSingularStringField(value: self.make, fieldNumber: 2)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 3)
    }
    if !self.year.isEmpty {
      try visitor.visitSingularStringField(value: self.year, fieldNumber: 4)
    }
    try { if let v = self._extra {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarVehicle, rhs: SmartcarVehicle) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.make != rhs.make {return false}
    if lhs.model != rhs.model {return false}
    if lhs.year != rhs.year {return false}
    if lhs._extra != rhs._extra {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarVehicleList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VehicleList"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}vehicles\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.vehicles) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vehicles, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarVehicleList, rhs: SmartcarVehicleList) -> Bool {
    if lhs.vehicles != rhs.vehicles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarReadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}make\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.make) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if !self.make.isEmpty {
      try visitor.visitSingularStringField(value: self.make, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarReadRequest, rhs: SmartcarReadRequest) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.make != rhs.make {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarClosureStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClosureStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarClosureStatus, rhs: SmartcarClosureStatus) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarOdometer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Odometer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}distance_km\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._distanceKm) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._distanceKm {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarOdometer, rhs: SmartcarOdometer) -> Bool {
    if lhs._distanceKm != rhs._distanceKm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarBatteryLevel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatteryLevel"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}percent_remaining\0\u{3}range_km\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._percentRemaining) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self._rangeKm) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._percentRemaining {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._rangeKm {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarBatteryLevel, rhs: SmartcarBatteryLevel) -> Bool {
    if lhs._percentRemaining != rhs._percentRemaining {return false}
    if lhs._rangeKm != rhs._rangeKm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarChargeLimit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChargeLimit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}limit\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._limit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._limit {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarChargeLimit, rhs: SmartcarChargeLimit) -> Bool {
    if lhs._limit != rhs._limit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarChargeStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChargeStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_plugged_in\0\u{1}state\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._isPluggedIn) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._state) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._isPluggedIn {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._state {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarChargeStatus, rhs: SmartcarChargeStatus) -> Bool {
    if lhs._isPluggedIn != rhs._isPluggedIn {return false}
    if lhs._state != rhs._state {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarNominalCapacity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NominalCapacity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capacity_kwh\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._capacityKwh) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._capacityKwh {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarNominalCapacity, rhs: SmartcarNominalCapacity) -> Bool {
    if lhs._capacityKwh != rhs._capacityKwh {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarTirePressure: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TirePressure"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}front_left_kpa\0\u{3}front_right_kpa\0\u{3}back_left_kpa\0\u{3}back_right_kpa\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._frontLeftKpa) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self._frontRightKpa) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self._backLeftKpa) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._backRightKpa) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._frontLeftKpa {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._frontRightKpa {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._backLeftKpa {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._backRightKpa {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarTirePressure, rhs: SmartcarTirePressure) -> Bool {
    if lhs._frontLeftKpa != rhs._frontLeftKpa {return false}
    if lhs._frontRightKpa != rhs._frontRightKpa {return false}
    if lhs._backLeftKpa != rhs._backLeftKpa {return false}
    if lhs._backRightKpa != rhs._backRightKpa {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarLockStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LockStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_locked\0\u{1}doors\0\u{1}windows\0\u{1}sunroof\0\u{1}storage\0\u{3}charging_port\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._isLocked) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.doors) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.windows) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.sunroof) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.storage) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.chargingPort) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._isLocked {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    if !self.doors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.doors, fieldNumber: 2)
    }
    if !self.windows.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.windows, fieldNumber: 3)
    }
    if !self.sunroof.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.sunroof, fieldNumber: 4)
    }
    if !self.storage.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.storage, fieldNumber: 5)
    }
    if !self.chargingPort.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chargingPort, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarLockStatus, rhs: SmartcarLockStatus) -> Bool {
    if lhs._isLocked != rhs._isLocked {return false}
    if lhs.doors != rhs.doors {return false}
    if lhs.windows != rhs.windows {return false}
    if lhs.sunroof != rhs.sunroof {return false}
    if lhs.storage != rhs.storage {return false}
    if lhs.chargingPort != rhs.chargingPort {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarEngineOil: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EngineOil"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}life_remaining\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._lifeRemaining) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._lifeRemaining {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarEngineOil, rhs: SmartcarEngineOil) -> Bool {
    if lhs._lifeRemaining != rhs._lifeRemaining {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarPermissions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Permissions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}permissions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.permissions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.permissions.isEmpty {
      try visitor.visitRepeatedStringField(value: self.permissions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarPermissions, rhs: SmartcarPermissions) -> Bool {
    if lhs.permissions != rhs.permissions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarTemperature: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Temperature"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}celsius\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._celsius) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._celsius {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarTemperature, rhs: SmartcarTemperature) -> Bool {
    if lhs._celsius != rhs._celsius {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarSpeedometer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Speedometer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}speed_kph\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._speedKph) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._speedKph {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarSpeedometer, rhs: SmartcarSpeedometer) -> Bool {
    if lhs._speedKph != rhs._speedKph {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarLookupVinRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LookupVinRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}vin\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vin) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vin.isEmpty {
      try visitor.visitSingularStringField(value: self.vin, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarLookupVinRequest, rhs: SmartcarLookupVinRequest) -> Bool {
    if lhs.vin != rhs.vin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarCabinClimate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CabinClimate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}on\0\u{3}temperature_celsius\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._on) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self._temperatureCelsius) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._on {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._temperatureCelsius {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarCabinClimate, rhs: SmartcarCabinClimate) -> Bool {
    if lhs._on != rhs._on {return false}
    if lhs._temperatureCelsius != rhs._temperatureCelsius {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarToggleState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ToggleState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}on\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._on) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._on {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarToggleState, rhs: SmartcarToggleState) -> Bool {
    if lhs._on != rhs._on {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarVehicleStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VehicleStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._status {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarVehicleStatus, rhs: SmartcarVehicleStatus) -> Bool {
    if lhs._status != rhs._status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarChargeControlRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChargeControlRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}action\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if self.action != .unspecified {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarChargeControlRequest, rhs: SmartcarChargeControlRequest) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.action != rhs.action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarCabinClimateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CabinClimateRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}action\0\u{3}temperature_celsius\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.temperatureCelsius) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if self.action != .unspecified {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 2)
    }
    if self.temperatureCelsius.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.temperatureCelsius, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarCabinClimateRequest, rhs: SmartcarCabinClimateRequest) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.action != rhs.action {return false}
    if lhs.temperatureCelsius != rhs.temperatureCelsius {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarDefrosterRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DefrosterRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}action\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if self.action != .unspecified {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarDefrosterRequest, rhs: SmartcarDefrosterRequest) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.action != rhs.action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarSteeringWheelRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SteeringWheelRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}action\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if self.action != .unspecified {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarSteeringWheelRequest, rhs: SmartcarSteeringWheelRequest) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.action != rhs.action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarSecurityRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SecurityRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}action\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if self.action != .unspecified {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarSecurityRequest, rhs: SmartcarSecurityRequest) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.action != rhs.action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarControlResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControlResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}action\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.action) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.action.isEmpty {
      try visitor.visitSingularStringField(value: self.action, fieldNumber: 1)
    }
    try { if let v = self._data {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SmartcarControlResponse, rhs: SmartcarControlResponse) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs._data != rhs._data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
