// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: smartcar.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Trimmed to the VIN-decode surface only. The upstream smartcar.proto also
// models connected-account reads/controls and the Connect OAuth flow; those
// messages are intentionally omitted here because WasmClient only wires the
// public `LookupVin` RPC (NHTSA vPIC decode, no connected account).
//
// Only `SmartcarVehicle` (the LookupVin response) and `SmartcarLookupVinRequest`
// are kept. Field numbers match the upstream definitions so wire encoding stays
// compatible with the wasm guest.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// One vehicle as decoded from a VIN (or one entry from a connected
/// account's garage). For `LookupVin`, `vehicleID` carries the queried VIN
/// and `extra` carries the raw NHTSA vPIC fields verbatim.
public struct SmartcarVehicle: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Stable per-vehicle identifier. For `LookupVin` this is the queried VIN.
  public var vehicleID: String = String()

  /// Manufacturer/brand string as reported by the backend (e.g. `"Tesla"`,
  /// `"Ford"`).
  public var make: String = String()

  /// Model name as reported by the backend. May be empty.
  public var model: String = String()

  /// Model year as reported by the backend. May be empty.
  public var year: String = String()

  /// Any additional per-vehicle fields the backend returns, forwarded
  /// verbatim without a fixed schema.
  public var extra: SwiftProtobuf.Google_Protobuf_Struct {
    get {_extra ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_extra = newValue}
  }
  /// Returns true if `extra` has been explicitly set.
  public var hasExtra: Bool {self._extra != nil}
  /// Clears the value of `extra`. Subsequent reads from it will return its default value.
  public mutating func clearExtra() {self._extra = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _extra: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

/// Request for the `LookupVin` RPC: decode a 17-character VIN.
public struct SmartcarLookupVinRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The 17-character VIN to decode.
  public var vin: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.smartcar"

extension SmartcarVehicle: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Vehicle"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}vehicle_id\0\u{1}make\0\u{1}model\0\u{1}year\0\u{1}extra\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vehicleID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.make) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.year) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._extra) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.vehicleID.isEmpty {
      try visitor.visitSingularStringField(value: self.vehicleID, fieldNumber: 1)
    }
    if !self.make.isEmpty {
      try visitor.visitSingularStringField(value: self.make, fieldNumber: 2)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 3)
    }
    if !self.year.isEmpty {
      try visitor.visitSingularStringField(value: self.year, fieldNumber: 4)
    }
    try { if let v = self._extra {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: SmartcarVehicle, 
rhs: SmartcarVehicle
) -> Bool {
    if lhs.vehicleID != rhs.vehicleID {return false}
    if lhs.make != rhs.make {return false}
    if lhs.model != rhs.model {return false}
    if lhs.year != rhs.year {return false}
    if lhs._extra != rhs._extra {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SmartcarLookupVinRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LookupVinRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}vin\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.vin) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vin.isEmpty {
      try visitor.visitSingularStringField(value: self.vin, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(
lhs: SmartcarLookupVinRequest, 
rhs: SmartcarLookupVinRequest
) -> Bool {
    if lhs.vin != rhs.vin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
