// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vision.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VisionScanRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// image file URI (file://) or URL (https://)
  public var file: String = String()

  /// scan category (default: "object")
  public var category: String {
    get {_category ?? String()}
    set {_category = newValue}
  }
  /// Returns true if `category` has been explicitly set.
  public var hasCategory: Bool {self._category != nil}
  /// Clears the value of `category`. Subsequent reads from it will return its default value.
  public mutating func clearCategory() {self._category = nil}

  /// localization language (default: "en")
  public var language: String {
    get {_language ?? String()}
    set {_language = newValue}
  }
  /// Returns true if `language` has been explicitly set.
  public var hasLanguage: Bool {self._language != nil}
  /// Clears the value of `language`. Subsequent reads from it will return its default value.
  public mutating func clearLanguage() {self._language = nil}

  /// custom analysis prompt
  public var prompt: String {
    get {_prompt ?? String()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  public var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  public mutating func clearPrompt() {self._prompt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _category: String? = nil
  fileprivate var _language: String? = nil
  fileprivate var _prompt: String? = nil
}

public struct VisionScanResult: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// AI-generated description/analysis
  public var description_p: String {
    get {_storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  /// follow-up questions
  public var suggestedQuestions: [String] {
    get {_storage._suggestedQuestions}
    set {_uniqueStorage()._suggestedQuestions = newValue}
  }

  /// identified object title
  public var title: String {
    get {_storage._title ?? String()}
    set {_uniqueStorage()._title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {_storage._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {_uniqueStorage()._title = nil}

  /// detected category
  public var categoryType: String {
    get {_storage._categoryType ?? String()}
    set {_uniqueStorage()._categoryType = newValue}
  }
  /// Returns true if `categoryType` has been explicitly set.
  public var hasCategoryType: Bool {_storage._categoryType != nil}
  /// Clears the value of `categoryType`. Subsequent reads from it will return its default value.
  public mutating func clearCategoryType() {_uniqueStorage()._categoryType = nil}

  /// uploaded image URL
  public var imageURL: String {
    get {_storage._imageURL ?? String()}
    set {_uniqueStorage()._imageURL = newValue}
  }
  /// Returns true if `imageURL` has been explicitly set.
  public var hasImageURL: Bool {_storage._imageURL != nil}
  /// Clears the value of `imageURL`. Subsequent reads from it will return its default value.
  public mutating func clearImageURL() {_uniqueStorage()._imageURL = nil}

  /// key-value characteristics
  public var characteristics: VisionCharacteristics {
    get {_storage._characteristics ?? VisionCharacteristics()}
    set {_uniqueStorage()._characteristics = newValue}
  }
  /// Returns true if `characteristics` has been explicitly set.
  public var hasCharacteristics: Bool {_storage._characteristics != nil}
  /// Clears the value of `characteristics`. Subsequent reads from it will return its default value.
  public mutating func clearCharacteristics() {_uniqueStorage()._characteristics = nil}

  /// food scans
  public var nutrition: VisionNutritionInfo {
    get {_storage._nutrition ?? VisionNutritionInfo()}
    set {_uniqueStorage()._nutrition = newValue}
  }
  /// Returns true if `nutrition` has been explicitly set.
  public var hasNutrition: Bool {_storage._nutrition != nil}
  /// Clears the value of `nutrition`. Subsequent reads from it will return its default value.
  public mutating func clearNutrition() {_uniqueStorage()._nutrition = nil}

  /// coin/stone scans
  public var physical: VisionPhysicalFeatures {
    get {_storage._physical ?? VisionPhysicalFeatures()}
    set {_uniqueStorage()._physical = newValue}
  }
  /// Returns true if `physical` has been explicitly set.
  public var hasPhysical: Bool {_storage._physical != nil}
  /// Clears the value of `physical`. Subsequent reads from it will return its default value.
  public mutating func clearPhysical() {_uniqueStorage()._physical = nil}

  /// market value
  public var price: VisionPriceInfo {
    get {_storage._price ?? VisionPriceInfo()}
    set {_uniqueStorage()._price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {_storage._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {_uniqueStorage()._price = nil}

  /// related products/links
  public var discoverMore: [VisionShoppingProduct] {
    get {_storage._discoverMore}
    set {_uniqueStorage()._discoverMore = newValue}
  }

  /// purchase links
  public var buyNow: [VisionLink] {
    get {_storage._buyNow}
    set {_uniqueStorage()._buyNow = newValue}
  }

  /// reference sources
  public var sources: [VisionLink] {
    get {_storage._sources}
    set {_uniqueStorage()._sources = newValue}
  }

  /// AI insights
  public var aiCommentary: VisionAICommentary {
    get {_storage._aiCommentary ?? VisionAICommentary()}
    set {_uniqueStorage()._aiCommentary = newValue}
  }
  /// Returns true if `aiCommentary` has been explicitly set.
  public var hasAiCommentary: Bool {_storage._aiCommentary != nil}
  /// Clears the value of `aiCommentary`. Subsequent reads from it will return its default value.
  public mutating func clearAiCommentary() {_uniqueStorage()._aiCommentary = nil}

  /// category-specific info block
  public var categoryInfo: VisionCategoryInfo {
    get {_storage._categoryInfo ?? VisionCategoryInfo()}
    set {_uniqueStorage()._categoryInfo = newValue}
  }
  /// Returns true if `categoryInfo` has been explicitly set.
  public var hasCategoryInfo: Bool {_storage._categoryInfo != nil}
  /// Clears the value of `categoryInfo`. Subsequent reads from it will return its default value.
  public mutating func clearCategoryInfo() {_uniqueStorage()._categoryInfo = nil}

  /// raw JSON response
  public var raw: String {
    get {_storage._raw ?? String()}
    set {_uniqueStorage()._raw = newValue}
  }
  /// Returns true if `raw` has been explicitly set.
  public var hasRaw: Bool {_storage._raw != nil}
  /// Clears the value of `raw`. Subsequent reads from it will return its default value.
  public mutating func clearRaw() {_uniqueStorage()._raw = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct VisionCharacteristics: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// key-value pairs
  public var fields: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VisionNutritionInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kcal: String {
    get {_kcal ?? String()}
    set {_kcal = newValue}
  }
  /// Returns true if `kcal` has been explicitly set.
  public var hasKcal: Bool {self._kcal != nil}
  /// Clears the value of `kcal`. Subsequent reads from it will return its default value.
  public mutating func clearKcal() {self._kcal = nil}

  public var calories: String {
    get {_calories ?? String()}
    set {_calories = newValue}
  }
  /// Returns true if `calories` has been explicitly set.
  public var hasCalories: Bool {self._calories != nil}
  /// Clears the value of `calories`. Subsequent reads from it will return its default value.
  public mutating func clearCalories() {self._calories = nil}

  public var protein: String {
    get {_protein ?? String()}
    set {_protein = newValue}
  }
  /// Returns true if `protein` has been explicitly set.
  public var hasProtein: Bool {self._protein != nil}
  /// Clears the value of `protein`. Subsequent reads from it will return its default value.
  public mutating func clearProtein() {self._protein = nil}

  public var carbs: String {
    get {_carbs ?? String()}
    set {_carbs = newValue}
  }
  /// Returns true if `carbs` has been explicitly set.
  public var hasCarbs: Bool {self._carbs != nil}
  /// Clears the value of `carbs`. Subsequent reads from it will return its default value.
  public mutating func clearCarbs() {self._carbs = nil}

  public var fat: String {
    get {_fat ?? String()}
    set {_fat = newValue}
  }
  /// Returns true if `fat` has been explicitly set.
  public var hasFat: Bool {self._fat != nil}
  /// Clears the value of `fat`. Subsequent reads from it will return its default value.
  public mutating func clearFat() {self._fat = nil}

  public var shelfLife: String {
    get {_shelfLife ?? String()}
    set {_shelfLife = newValue}
  }
  /// Returns true if `shelfLife` has been explicitly set.
  public var hasShelfLife: Bool {self._shelfLife != nil}
  /// Clears the value of `shelfLife`. Subsequent reads from it will return its default value.
  public mutating func clearShelfLife() {self._shelfLife = nil}

  public var freshness: String {
    get {_freshness ?? String()}
    set {_freshness = newValue}
  }
  /// Returns true if `freshness` has been explicitly set.
  public var hasFreshness: Bool {self._freshness != nil}
  /// Clears the value of `freshness`. Subsequent reads from it will return its default value.
  public mutating func clearFreshness() {self._freshness = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _kcal: String? = nil
  fileprivate var _calories: String? = nil
  fileprivate var _protein: String? = nil
  fileprivate var _carbs: String? = nil
  fileprivate var _fat: String? = nil
  fileprivate var _shelfLife: String? = nil
  fileprivate var _freshness: String? = nil
}

public struct VisionPhysicalFeatures: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var weight: String {
    get {_storage._weight ?? String()}
    set {_uniqueStorage()._weight = newValue}
  }
  /// Returns true if `weight` has been explicitly set.
  public var hasWeight: Bool {_storage._weight != nil}
  /// Clears the value of `weight`. Subsequent reads from it will return its default value.
  public mutating func clearWeight() {_uniqueStorage()._weight = nil}

  public var diameter: String {
    get {_storage._diameter ?? String()}
    set {_uniqueStorage()._diameter = newValue}
  }
  /// Returns true if `diameter` has been explicitly set.
  public var hasDiameter: Bool {_storage._diameter != nil}
  /// Clears the value of `diameter`. Subsequent reads from it will return its default value.
  public mutating func clearDiameter() {_uniqueStorage()._diameter = nil}

  public var thickness: String {
    get {_storage._thickness ?? String()}
    set {_uniqueStorage()._thickness = newValue}
  }
  /// Returns true if `thickness` has been explicitly set.
  public var hasThickness: Bool {_storage._thickness != nil}
  /// Clears the value of `thickness`. Subsequent reads from it will return its default value.
  public mutating func clearThickness() {_uniqueStorage()._thickness = nil}

  public var edge: String {
    get {_storage._edge ?? String()}
    set {_uniqueStorage()._edge = newValue}
  }
  /// Returns true if `edge` has been explicitly set.
  public var hasEdge: Bool {_storage._edge != nil}
  /// Clears the value of `edge`. Subsequent reads from it will return its default value.
  public mutating func clearEdge() {_uniqueStorage()._edge = nil}

  public var composition: String {
    get {_storage._composition ?? String()}
    set {_uniqueStorage()._composition = newValue}
  }
  /// Returns true if `composition` has been explicitly set.
  public var hasComposition: Bool {_storage._composition != nil}
  /// Clears the value of `composition`. Subsequent reads from it will return its default value.
  public mutating func clearComposition() {_uniqueStorage()._composition = nil}

  public var mintage: String {
    get {_storage._mintage ?? String()}
    set {_uniqueStorage()._mintage = newValue}
  }
  /// Returns true if `mintage` has been explicitly set.
  public var hasMintage: Bool {_storage._mintage != nil}
  /// Clears the value of `mintage`. Subsequent reads from it will return its default value.
  public mutating func clearMintage() {_uniqueStorage()._mintage = nil}

  public var yearsOfMinting: String {
    get {_storage._yearsOfMinting ?? String()}
    set {_uniqueStorage()._yearsOfMinting = newValue}
  }
  /// Returns true if `yearsOfMinting` has been explicitly set.
  public var hasYearsOfMinting: Bool {_storage._yearsOfMinting != nil}
  /// Clears the value of `yearsOfMinting`. Subsequent reads from it will return its default value.
  public mutating func clearYearsOfMinting() {_uniqueStorage()._yearsOfMinting = nil}

  public var grade: String {
    get {_storage._grade ?? String()}
    set {_uniqueStorage()._grade = newValue}
  }
  /// Returns true if `grade` has been explicitly set.
  public var hasGrade: Bool {_storage._grade != nil}
  /// Clears the value of `grade`. Subsequent reads from it will return its default value.
  public mutating func clearGrade() {_uniqueStorage()._grade = nil}

  public var krauseNumber: String {
    get {_storage._krauseNumber ?? String()}
    set {_uniqueStorage()._krauseNumber = newValue}
  }
  /// Returns true if `krauseNumber` has been explicitly set.
  public var hasKrauseNumber: Bool {_storage._krauseNumber != nil}
  /// Clears the value of `krauseNumber`. Subsequent reads from it will return its default value.
  public mutating func clearKrauseNumber() {_uniqueStorage()._krauseNumber = nil}

  public var issuer: String {
    get {_storage._issuer ?? String()}
    set {_uniqueStorage()._issuer = newValue}
  }
  /// Returns true if `issuer` has been explicitly set.
  public var hasIssuer: Bool {_storage._issuer != nil}
  /// Clears the value of `issuer`. Subsequent reads from it will return its default value.
  public mutating func clearIssuer() {_uniqueStorage()._issuer = nil}

  public var rarity: String {
    get {_storage._rarity ?? String()}
    set {_uniqueStorage()._rarity = newValue}
  }
  /// Returns true if `rarity` has been explicitly set.
  public var hasRarity: Bool {_storage._rarity != nil}
  /// Clears the value of `rarity`. Subsequent reads from it will return its default value.
  public mutating func clearRarity() {_uniqueStorage()._rarity = nil}

  public var hardnessScale: String {
    get {_storage._hardnessScale ?? String()}
    set {_uniqueStorage()._hardnessScale = newValue}
  }
  /// Returns true if `hardnessScale` has been explicitly set.
  public var hasHardnessScale: Bool {_storage._hardnessScale != nil}
  /// Clears the value of `hardnessScale`. Subsequent reads from it will return its default value.
  public mutating func clearHardnessScale() {_uniqueStorage()._hardnessScale = nil}

  public var density: String {
    get {_storage._density ?? String()}
    set {_uniqueStorage()._density = newValue}
  }
  /// Returns true if `density` has been explicitly set.
  public var hasDensity: Bool {_storage._density != nil}
  /// Clears the value of `density`. Subsequent reads from it will return its default value.
  public mutating func clearDensity() {_uniqueStorage()._density = nil}

  public var crystalSystem: String {
    get {_storage._crystalSystem ?? String()}
    set {_uniqueStorage()._crystalSystem = newValue}
  }
  /// Returns true if `crystalSystem` has been explicitly set.
  public var hasCrystalSystem: Bool {_storage._crystalSystem != nil}
  /// Clears the value of `crystalSystem`. Subsequent reads from it will return its default value.
  public mutating func clearCrystalSystem() {_uniqueStorage()._crystalSystem = nil}

  public var luster: String {
    get {_storage._luster ?? String()}
    set {_uniqueStorage()._luster = newValue}
  }
  /// Returns true if `luster` has been explicitly set.
  public var hasLuster: Bool {_storage._luster != nil}
  /// Clears the value of `luster`. Subsequent reads from it will return its default value.
  public mutating func clearLuster() {_uniqueStorage()._luster = nil}

  public var formula: String {
    get {_storage._formula ?? String()}
    set {_uniqueStorage()._formula = newValue}
  }
  /// Returns true if `formula` has been explicitly set.
  public var hasFormula: Bool {_storage._formula != nil}
  /// Clears the value of `formula`. Subsequent reads from it will return its default value.
  public mutating func clearFormula() {_uniqueStorage()._formula = nil}

  public var color: String {
    get {_storage._color ?? String()}
    set {_uniqueStorage()._color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  public var hasColor: Bool {_storage._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  public mutating func clearColor() {_uniqueStorage()._color = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct VisionPriceInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var averageFairMarketPrice: String {
    get {_averageFairMarketPrice ?? String()}
    set {_averageFairMarketPrice = newValue}
  }
  /// Returns true if `averageFairMarketPrice` has been explicitly set.
  public var hasAverageFairMarketPrice: Bool {self._averageFairMarketPrice != nil}
  /// Clears the value of `averageFairMarketPrice`. Subsequent reads from it will return its default value.
  public mutating func clearAverageFairMarketPrice() {self._averageFairMarketPrice = nil}

  public var webPurchaseURL: String {
    get {_webPurchaseURL ?? String()}
    set {_webPurchaseURL = newValue}
  }
  /// Returns true if `webPurchaseURL` has been explicitly set.
  public var hasWebPurchaseURL: Bool {self._webPurchaseURL != nil}
  /// Clears the value of `webPurchaseURL`. Subsequent reads from it will return its default value.
  public mutating func clearWebPurchaseURL() {self._webPurchaseURL = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _averageFairMarketPrice: String? = nil
  fileprivate var _webPurchaseURL: String? = nil
}

public struct VisionLink: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String {
    get {_title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var url: String {
    get {_url ?? String()}
    set {_url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  public var hasURL: Bool {self._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  public mutating func clearURL() {self._url = nil}

  public var description_p: String {
    get {_description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var image: String {
    get {_image ?? String()}
    set {_image = newValue}
  }
  /// Returns true if `image` has been explicitly set.
  public var hasImage: Bool {self._image != nil}
  /// Clears the value of `image`. Subsequent reads from it will return its default value.
  public mutating func clearImage() {self._image = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _title: String? = nil
  fileprivate var _url: String? = nil
  fileprivate var _description_p: String? = nil
  fileprivate var _image: String? = nil
}

public struct VisionAICommentary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var aiAssistantSays: String {
    get {_aiAssistantSays ?? String()}
    set {_aiAssistantSays = newValue}
  }
  /// Returns true if `aiAssistantSays` has been explicitly set.
  public var hasAiAssistantSays: Bool {self._aiAssistantSays != nil}
  /// Clears the value of `aiAssistantSays`. Subsequent reads from it will return its default value.
  public mutating func clearAiAssistantSays() {self._aiAssistantSays = nil}

  public var aiSuggests: String {
    get {_aiSuggests ?? String()}
    set {_aiSuggests = newValue}
  }
  /// Returns true if `aiSuggests` has been explicitly set.
  public var hasAiSuggests: Bool {self._aiSuggests != nil}
  /// Clears the value of `aiSuggests`. Subsequent reads from it will return its default value.
  public mutating func clearAiSuggests() {self._aiSuggests = nil}

  public var expertInsights: String {
    get {_expertInsights ?? String()}
    set {_expertInsights = newValue}
  }
  /// Returns true if `expertInsights` has been explicitly set.
  public var hasExpertInsights: Bool {self._expertInsights != nil}
  /// Clears the value of `expertInsights`. Subsequent reads from it will return its default value.
  public mutating func clearExpertInsights() {self._expertInsights = nil}

  public var recommendation: String {
    get {_recommendation ?? String()}
    set {_recommendation = newValue}
  }
  /// Returns true if `recommendation` has been explicitly set.
  public var hasRecommendation: Bool {self._recommendation != nil}
  /// Clears the value of `recommendation`. Subsequent reads from it will return its default value.
  public mutating func clearRecommendation() {self._recommendation = nil}

  public var interestingFacts: String {
    get {_interestingFacts ?? String()}
    set {_interestingFacts = newValue}
  }
  /// Returns true if `interestingFacts` has been explicitly set.
  public var hasInterestingFacts: Bool {self._interestingFacts != nil}
  /// Clears the value of `interestingFacts`. Subsequent reads from it will return its default value.
  public mutating func clearInterestingFacts() {self._interestingFacts = nil}

  public var learnMore: String {
    get {_learnMore ?? String()}
    set {_learnMore = newValue}
  }
  /// Returns true if `learnMore` has been explicitly set.
  public var hasLearnMore: Bool {self._learnMore != nil}
  /// Clears the value of `learnMore`. Subsequent reads from it will return its default value.
  public mutating func clearLearnMore() {self._learnMore = nil}

  public var realOrFake: String {
    get {_realOrFake ?? String()}
    set {_realOrFake = newValue}
  }
  /// Returns true if `realOrFake` has been explicitly set.
  public var hasRealOrFake: Bool {self._realOrFake != nil}
  /// Clears the value of `realOrFake`. Subsequent reads from it will return its default value.
  public mutating func clearRealOrFake() {self._realOrFake = nil}

  public var marketDemand: String {
    get {_marketDemand ?? String()}
    set {_marketDemand = newValue}
  }
  /// Returns true if `marketDemand` has been explicitly set.
  public var hasMarketDemand: Bool {self._marketDemand != nil}
  /// Clears the value of `marketDemand`. Subsequent reads from it will return its default value.
  public mutating func clearMarketDemand() {self._marketDemand = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _aiAssistantSays: String? = nil
  fileprivate var _aiSuggests: String? = nil
  fileprivate var _expertInsights: String? = nil
  fileprivate var _recommendation: String? = nil
  fileprivate var _interestingFacts: String? = nil
  fileprivate var _learnMore: String? = nil
  fileprivate var _realOrFake: String? = nil
  fileprivate var _marketDemand: String? = nil
}

public struct VisionCategoryInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// info block type (coinInfo, foodInfo, etc.)
  public var type: String = String()

  /// category-specific fields
  public var fields: Dictionary<String,String> = [:]

  /// nested structured data
  public var metadata: SwiftProtobuf.Google_Protobuf_Struct {
    get {_metadata ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _metadata: SwiftProtobuf.Google_Protobuf_Struct? = nil
}

public struct VisionShoppingProduct: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String {
    get {_title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var price: String {
    get {_price ?? String()}
    set {_price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {self._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {self._price = nil}

  public var currency: String {
    get {_currency ?? String()}
    set {_currency = newValue}
  }
  /// Returns true if `currency` has been explicitly set.
  public var hasCurrency: Bool {self._currency != nil}
  /// Clears the value of `currency`. Subsequent reads from it will return its default value.
  public mutating func clearCurrency() {self._currency = nil}

  public var url: String {
    get {_url ?? String()}
    set {_url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  public var hasURL: Bool {self._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  public mutating func clearURL() {self._url = nil}

  public var image: String {
    get {_image ?? String()}
    set {_image = newValue}
  }
  /// Returns true if `image` has been explicitly set.
  public var hasImage: Bool {self._image != nil}
  /// Clears the value of `image`. Subsequent reads from it will return its default value.
  public mutating func clearImage() {self._image = nil}

  /// e.g. "google", "amazon"
  public var source: String {
    get {_source ?? String()}
    set {_source = newValue}
  }
  /// Returns true if `source` has been explicitly set.
  public var hasSource: Bool {self._source != nil}
  /// Clears the value of `source`. Subsequent reads from it will return its default value.
  public mutating func clearSource() {self._source = nil}

  public var rating: Double {
    get {_rating ?? 0}
    set {_rating = newValue}
  }
  /// Returns true if `rating` has been explicitly set.
  public var hasRating: Bool {self._rating != nil}
  /// Clears the value of `rating`. Subsequent reads from it will return its default value.
  public mutating func clearRating() {self._rating = nil}

  public var reviewsCount: Int32 {
    get {_reviewsCount ?? 0}
    set {_reviewsCount = newValue}
  }
  /// Returns true if `reviewsCount` has been explicitly set.
  public var hasReviewsCount: Bool {self._reviewsCount != nil}
  /// Clears the value of `reviewsCount`. Subsequent reads from it will return its default value.
  public mutating func clearReviewsCount() {self._reviewsCount = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _title: String? = nil
  fileprivate var _price: String? = nil
  fileprivate var _currency: String? = nil
  fileprivate var _url: String? = nil
  fileprivate var _image: String? = nil
  fileprivate var _source: String? = nil
  fileprivate var _rating: Double? = nil
  fileprivate var _reviewsCount: Int32? = nil
}

public struct VisionShoppingResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var products: [VisionShoppingProduct] = []

  /// search query used
  public var query: String {
    get {_query ?? String()}
    set {_query = newValue}
  }
  /// Returns true if `query` has been explicitly set.
  public var hasQuery: Bool {self._query != nil}
  /// Clears the value of `query`. Subsequent reads from it will return its default value.
  public mutating func clearQuery() {self._query = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _query: String? = nil
}

public struct VisionVideoResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String {
    get {_title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var url: String {
    get {_url ?? String()}
    set {_url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  public var hasURL: Bool {self._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  public mutating func clearURL() {self._url = nil}

  public var thumbnail: String {
    get {_thumbnail ?? String()}
    set {_thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  public var hasThumbnail: Bool {self._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  public mutating func clearThumbnail() {self._thumbnail = nil}

  /// e.g. "youtube"
  public var source: String {
    get {_source ?? String()}
    set {_source = newValue}
  }
  /// Returns true if `source` has been explicitly set.
  public var hasSource: Bool {self._source != nil}
  /// Clears the value of `source`. Subsequent reads from it will return its default value.
  public mutating func clearSource() {self._source = nil}

  public var duration: String {
    get {_duration ?? String()}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _title: String? = nil
  fileprivate var _url: String? = nil
  fileprivate var _thumbnail: String? = nil
  fileprivate var _source: String? = nil
  fileprivate var _duration: String? = nil
}

public struct VisionRecipeResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String {
    get {_title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var url: String {
    get {_url ?? String()}
    set {_url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  public var hasURL: Bool {self._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  public mutating func clearURL() {self._url = nil}

  public var image: String {
    get {_image ?? String()}
    set {_image = newValue}
  }
  /// Returns true if `image` has been explicitly set.
  public var hasImage: Bool {self._image != nil}
  /// Clears the value of `image`. Subsequent reads from it will return its default value.
  public mutating func clearImage() {self._image = nil}

  public var source: String {
    get {_source ?? String()}
    set {_source = newValue}
  }
  /// Returns true if `source` has been explicitly set.
  public var hasSource: Bool {self._source != nil}
  /// Clears the value of `source`. Subsequent reads from it will return its default value.
  public mutating func clearSource() {self._source = nil}

  public var cookTime: String {
    get {_cookTime ?? String()}
    set {_cookTime = newValue}
  }
  /// Returns true if `cookTime` has been explicitly set.
  public var hasCookTime: Bool {self._cookTime != nil}
  /// Clears the value of `cookTime`. Subsequent reads from it will return its default value.
  public mutating func clearCookTime() {self._cookTime = nil}

  public var rating: Double {
    get {_rating ?? 0}
    set {_rating = newValue}
  }
  /// Returns true if `rating` has been explicitly set.
  public var hasRating: Bool {self._rating != nil}
  /// Clears the value of `rating`. Subsequent reads from it will return its default value.
  public mutating func clearRating() {self._rating = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _title: String? = nil
  fileprivate var _url: String? = nil
  fileprivate var _image: String? = nil
  fileprivate var _source: String? = nil
  fileprivate var _cookTime: String? = nil
  fileprivate var _rating: Double? = nil
}

public struct VisionDiscoverResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var products: [VisionShoppingProduct] = []

  public var videos: [VisionVideoResult] = []

  public var recipes: [VisionRecipeResult] = []

  public var relatedLinks: [VisionLink] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VisionExtendedScanResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// base scan result
  public var scan: VisionScanResult {
    get {_scan ?? VisionScanResult()}
    set {_scan = newValue}
  }
  /// Returns true if `scan` has been explicitly set.
  public var hasScan: Bool {self._scan != nil}
  /// Clears the value of `scan`. Subsequent reads from it will return its default value.
  public mutating func clearScan() {self._scan = nil}

  /// buy now products
  public var shopping: VisionShoppingResult {
    get {_shopping ?? VisionShoppingResult()}
    set {_shopping = newValue}
  }
  /// Returns true if `shopping` has been explicitly set.
  public var hasShopping: Bool {self._shopping != nil}
  /// Clears the value of `shopping`. Subsequent reads from it will return its default value.
  public mutating func clearShopping() {self._shopping = nil}

  /// related content
  public var discover: VisionDiscoverResult {
    get {_discover ?? VisionDiscoverResult()}
    set {_discover = newValue}
  }
  /// Returns true if `discover` has been explicitly set.
  public var hasDiscover: Bool {self._discover != nil}
  /// Clears the value of `discover`. Subsequent reads from it will return its default value.
  public mutating func clearDiscover() {self._discover = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _scan: VisionScanResult? = nil
  fileprivate var _shopping: VisionShoppingResult? = nil
  fileprivate var _discover: VisionDiscoverResult? = nil
}

public struct VisionScanHistoryItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var title: String = String()

  public var categoryType: String {
    get {_categoryType ?? String()}
    set {_categoryType = newValue}
  }
  /// Returns true if `categoryType` has been explicitly set.
  public var hasCategoryType: Bool {self._categoryType != nil}
  /// Clears the value of `categoryType`. Subsequent reads from it will return its default value.
  public mutating func clearCategoryType() {self._categoryType = nil}

  public var imageURL: String {
    get {_imageURL ?? String()}
    set {_imageURL = newValue}
  }
  /// Returns true if `imageURL` has been explicitly set.
  public var hasImageURL: Bool {self._imageURL != nil}
  /// Clears the value of `imageURL`. Subsequent reads from it will return its default value.
  public mutating func clearImageURL() {self._imageURL = nil}

  public var thumbnail: String {
    get {_thumbnail ?? String()}
    set {_thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  public var hasThumbnail: Bool {self._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  public mutating func clearThumbnail() {self._thumbnail = nil}

  public var createdAt: Int64 {
    get {_createdAt ?? 0}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _categoryType: String? = nil
  fileprivate var _imageURL: String? = nil
  fileprivate var _thumbnail: String? = nil
  fileprivate var _createdAt: Int64? = nil
}

public struct VisionScanHistoryList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var items: [VisionScanHistoryItem] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.vision"

extension VisionScanRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScanRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}file\0\u{1}category\0\u{1}language\0\u{1}prompt\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.file) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._category) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._language) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._prompt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.file.isEmpty {
      try visitor.visitSingularStringField(value: self.file, fieldNumber: 1)
    }
    try { if let v = self._category {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._language {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._prompt {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionScanRequest, rhs: VisionScanRequest) -> Bool {
    if lhs.file != rhs.file {return false}
    if lhs._category != rhs._category {return false}
    if lhs._language != rhs._language {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionScanResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScanResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}description\0\u{3}suggested_questions\0\u{1}title\0\u{3}category_type\0\u{3}image_url\0\u{1}characteristics\0\u{1}nutrition\0\u{1}physical\0\u{1}price\0\u{3}discover_more\0\u{3}buy_now\0\u{1}sources\0\u{3}ai_commentary\0\u{3}category_info\0\u{1}raw\0")

  fileprivate class _StorageClass {
    var _description_p: String = String()
    var _suggestedQuestions: [String] = []
    var _title: String? = nil
    var _categoryType: String? = nil
    var _imageURL: String? = nil
    var _characteristics: VisionCharacteristics? = nil
    var _nutrition: VisionNutritionInfo? = nil
    var _physical: VisionPhysicalFeatures? = nil
    var _price: VisionPriceInfo? = nil
    var _discoverMore: [VisionShoppingProduct] = []
    var _buyNow: [VisionLink] = []
    var _sources: [VisionLink] = []
    var _aiCommentary: VisionAICommentary? = nil
    var _categoryInfo: VisionCategoryInfo? = nil
    var _raw: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _description_p = source._description_p
      _suggestedQuestions = source._suggestedQuestions
      _title = source._title
      _categoryType = source._categoryType
      _imageURL = source._imageURL
      _characteristics = source._characteristics
      _nutrition = source._nutrition
      _physical = source._physical
      _price = source._price
      _discoverMore = source._discoverMore
      _buyNow = source._buyNow
      _sources = source._sources
      _aiCommentary = source._aiCommentary
      _categoryInfo = source._categoryInfo
      _raw = source._raw
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 2: try { try decoder.decodeRepeatedStringField(value: &_storage._suggestedQuestions) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._categoryType) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._imageURL) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._characteristics) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._nutrition) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._physical) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._price) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._discoverMore) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._buyNow) }()
        case 12: try { try decoder.decodeRepeatedMessageField(value: &_storage._sources) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._aiCommentary) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._categoryInfo) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._raw) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 1)
      }
      if !_storage._suggestedQuestions.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._suggestedQuestions, fieldNumber: 2)
      }
      try { if let v = _storage._title {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._categoryType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._imageURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._characteristics {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._nutrition {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._physical {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._price {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if !_storage._discoverMore.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._discoverMore, fieldNumber: 10)
      }
      if !_storage._buyNow.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._buyNow, fieldNumber: 11)
      }
      if !_storage._sources.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._sources, fieldNumber: 12)
      }
      try { if let v = _storage._aiCommentary {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._categoryInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._raw {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionScanResult, rhs: VisionScanResult) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._suggestedQuestions != rhs_storage._suggestedQuestions {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._categoryType != rhs_storage._categoryType {return false}
        if _storage._imageURL != rhs_storage._imageURL {return false}
        if _storage._characteristics != rhs_storage._characteristics {return false}
        if _storage._nutrition != rhs_storage._nutrition {return false}
        if _storage._physical != rhs_storage._physical {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._discoverMore != rhs_storage._discoverMore {return false}
        if _storage._buyNow != rhs_storage._buyNow {return false}
        if _storage._sources != rhs_storage._sources {return false}
        if _storage._aiCommentary != rhs_storage._aiCommentary {return false}
        if _storage._categoryInfo != rhs_storage._categoryInfo {return false}
        if _storage._raw != rhs_storage._raw {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionCharacteristics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Characteristics"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fields\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.fields) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fields.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.fields, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionCharacteristics, rhs: VisionCharacteristics) -> Bool {
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionNutritionInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NutritionInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kcal\0\u{1}calories\0\u{1}protein\0\u{1}carbs\0\u{1}fat\0\u{1}shelf_life\0\u{1}freshness\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._kcal) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._calories) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._protein) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._carbs) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._fat) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._shelfLife) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._freshness) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._kcal {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._calories {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._protein {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._carbs {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._fat {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._shelfLife {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._freshness {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionNutritionInfo, rhs: VisionNutritionInfo) -> Bool {
    if lhs._kcal != rhs._kcal {return false}
    if lhs._calories != rhs._calories {return false}
    if lhs._protein != rhs._protein {return false}
    if lhs._carbs != rhs._carbs {return false}
    if lhs._fat != rhs._fat {return false}
    if lhs._shelfLife != rhs._shelfLife {return false}
    if lhs._freshness != rhs._freshness {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionPhysicalFeatures: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhysicalFeatures"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}weight\0\u{1}diameter\0\u{1}thickness\0\u{1}edge\0\u{1}composition\0\u{1}mintage\0\u{1}years_of_minting\0\u{1}grade\0\u{1}krause_number\0\u{1}issuer\0\u{1}rarity\0\u{1}hardness_scale\0\u{1}density\0\u{1}crystal_system\0\u{1}luster\0\u{1}formula\0\u{1}color\0")

  fileprivate class _StorageClass {
    var _weight: String? = nil
    var _diameter: String? = nil
    var _thickness: String? = nil
    var _edge: String? = nil
    var _composition: String? = nil
    var _mintage: String? = nil
    var _yearsOfMinting: String? = nil
    var _grade: String? = nil
    var _krauseNumber: String? = nil
    var _issuer: String? = nil
    var _rarity: String? = nil
    var _hardnessScale: String? = nil
    var _density: String? = nil
    var _crystalSystem: String? = nil
    var _luster: String? = nil
    var _formula: String? = nil
    var _color: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _weight = source._weight
      _diameter = source._diameter
      _thickness = source._thickness
      _edge = source._edge
      _composition = source._composition
      _mintage = source._mintage
      _yearsOfMinting = source._yearsOfMinting
      _grade = source._grade
      _krauseNumber = source._krauseNumber
      _issuer = source._issuer
      _rarity = source._rarity
      _hardnessScale = source._hardnessScale
      _density = source._density
      _crystalSystem = source._crystalSystem
      _luster = source._luster
      _formula = source._formula
      _color = source._color
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._weight) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._diameter) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._thickness) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._edge) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._composition) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._mintage) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._yearsOfMinting) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._grade) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._krauseNumber) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._issuer) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._rarity) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._hardnessScale) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._density) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._crystalSystem) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._luster) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._formula) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._color) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._weight {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._diameter {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._thickness {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._edge {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._composition {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._mintage {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._yearsOfMinting {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._grade {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._krauseNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._issuer {
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._rarity {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._hardnessScale {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._density {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._crystalSystem {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._luster {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._formula {
        try visitor.visitSingularStringField(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._color {
        try visitor.visitSingularStringField(value: v, fieldNumber: 17)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionPhysicalFeatures, rhs: VisionPhysicalFeatures) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._weight != rhs_storage._weight {return false}
        if _storage._diameter != rhs_storage._diameter {return false}
        if _storage._thickness != rhs_storage._thickness {return false}
        if _storage._edge != rhs_storage._edge {return false}
        if _storage._composition != rhs_storage._composition {return false}
        if _storage._mintage != rhs_storage._mintage {return false}
        if _storage._yearsOfMinting != rhs_storage._yearsOfMinting {return false}
        if _storage._grade != rhs_storage._grade {return false}
        if _storage._krauseNumber != rhs_storage._krauseNumber {return false}
        if _storage._issuer != rhs_storage._issuer {return false}
        if _storage._rarity != rhs_storage._rarity {return false}
        if _storage._hardnessScale != rhs_storage._hardnessScale {return false}
        if _storage._density != rhs_storage._density {return false}
        if _storage._crystalSystem != rhs_storage._crystalSystem {return false}
        if _storage._luster != rhs_storage._luster {return false}
        if _storage._formula != rhs_storage._formula {return false}
        if _storage._color != rhs_storage._color {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionPriceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PriceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}average_fair_market_price\0\u{3}web_purchase_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._averageFairMarketPrice) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._webPurchaseURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._averageFairMarketPrice {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._webPurchaseURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionPriceInfo, rhs: VisionPriceInfo) -> Bool {
    if lhs._averageFairMarketPrice != rhs._averageFairMarketPrice {return false}
    if lhs._webPurchaseURL != rhs._webPurchaseURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionLink: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Link"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}url\0\u{1}description\0\u{1}image\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._url) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._image) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._url {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._image {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionLink, rhs: VisionLink) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._url != rhs._url {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._image != rhs._image {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionAICommentary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AICommentary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ai_assistant_says\0\u{1}ai_suggests\0\u{1}expert_insights\0\u{1}recommendation\0\u{1}interesting_facts\0\u{1}learn_more\0\u{1}real_or_fake\0\u{5}market_demand\0market_demand_and_value_analysis\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._aiAssistantSays) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._aiSuggests) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._expertInsights) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._recommendation) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._interestingFacts) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._learnMore) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._realOrFake) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._marketDemand) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._aiAssistantSays {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._aiSuggests {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._expertInsights {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._recommendation {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._interestingFacts {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._learnMore {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._realOrFake {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._marketDemand {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionAICommentary, rhs: VisionAICommentary) -> Bool {
    if lhs._aiAssistantSays != rhs._aiAssistantSays {return false}
    if lhs._aiSuggests != rhs._aiSuggests {return false}
    if lhs._expertInsights != rhs._expertInsights {return false}
    if lhs._recommendation != rhs._recommendation {return false}
    if lhs._interestingFacts != rhs._interestingFacts {return false}
    if lhs._learnMore != rhs._learnMore {return false}
    if lhs._realOrFake != rhs._realOrFake {return false}
    if lhs._marketDemand != rhs._marketDemand {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionCategoryInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CategoryInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}fields\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.fields) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.fields.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.fields, fieldNumber: 2)
    }
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionCategoryInfo, rhs: VisionCategoryInfo) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.fields != rhs.fields {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionShoppingProduct: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ShoppingProduct"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}price\0\u{1}currency\0\u{1}url\0\u{1}image\0\u{1}source\0\u{1}rating\0\u{1}reviews_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._price) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._currency) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._url) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._image) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._rating) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._reviewsCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._price {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._currency {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._url {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._image {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._rating {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._reviewsCount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionShoppingProduct, rhs: VisionShoppingProduct) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._price != rhs._price {return false}
    if lhs._currency != rhs._currency {return false}
    if lhs._url != rhs._url {return false}
    if lhs._image != rhs._image {return false}
    if lhs._source != rhs._source {return false}
    if lhs._rating != rhs._rating {return false}
    if lhs._reviewsCount != rhs._reviewsCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionShoppingResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ShoppingResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}products\0\u{1}query\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.products) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._query) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.products.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.products, fieldNumber: 1)
    }
    try { if let v = self._query {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionShoppingResult, rhs: VisionShoppingResult) -> Bool {
    if lhs.products != rhs.products {return false}
    if lhs._query != rhs._query {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionVideoResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}url\0\u{1}thumbnail\0\u{1}source\0\u{1}duration\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._url) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._thumbnail) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._duration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._url {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._thumbnail {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionVideoResult, rhs: VisionVideoResult) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._url != rhs._url {return false}
    if lhs._thumbnail != rhs._thumbnail {return false}
    if lhs._source != rhs._source {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionRecipeResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecipeResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}url\0\u{1}image\0\u{1}source\0\u{1}cook_time\0\u{1}rating\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._url) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._image) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._cookTime) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._rating) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._url {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._image {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._cookTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._rating {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionRecipeResult, rhs: VisionRecipeResult) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._url != rhs._url {return false}
    if lhs._image != rhs._image {return false}
    if lhs._source != rhs._source {return false}
    if lhs._cookTime != rhs._cookTime {return false}
    if lhs._rating != rhs._rating {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionDiscoverResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DiscoverResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}products\0\u{1}videos\0\u{1}recipes\0\u{1}related_links\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.products) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.videos) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.recipes) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.relatedLinks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.products.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.products, fieldNumber: 1)
    }
    if !self.videos.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.videos, fieldNumber: 2)
    }
    if !self.recipes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.recipes, fieldNumber: 3)
    }
    if !self.relatedLinks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.relatedLinks, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionDiscoverResult, rhs: VisionDiscoverResult) -> Bool {
    if lhs.products != rhs.products {return false}
    if lhs.videos != rhs.videos {return false}
    if lhs.recipes != rhs.recipes {return false}
    if lhs.relatedLinks != rhs.relatedLinks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionExtendedScanResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExtendedScanResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}scan\0\u{1}shopping\0\u{1}discover\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._scan) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._shopping) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._discover) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._scan {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._shopping {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._discover {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionExtendedScanResult, rhs: VisionExtendedScanResult) -> Bool {
    if lhs._scan != rhs._scan {return false}
    if lhs._shopping != rhs._shopping {return false}
    if lhs._discover != rhs._discover {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionScanHistoryItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScanHistoryItem"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}title\0\u{3}category_type\0\u{3}image_url\0\u{1}thumbnail\0\u{3}created_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._categoryType) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._imageURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._thumbnail) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self._createdAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    try { if let v = self._categoryType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._imageURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._thumbnail {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._createdAt {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionScanHistoryItem, rhs: VisionScanHistoryItem) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs._categoryType != rhs._categoryType {return false}
    if lhs._imageURL != rhs._imageURL {return false}
    if lhs._thumbnail != rhs._thumbnail {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VisionScanHistoryList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScanHistoryList"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}items\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VisionScanHistoryList, rhs: VisionScanHistoryList) -> Bool {
    if lhs.items != rhs.items {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
