load("@build_bazel_rules_swift//swift:swift_library.bzl", "swift_library")

swift_library(
    name = "WasmClient",
    srcs = [
        "Interface.swift",
        "Mocks.swift",
        "Models/AIArt.swift",
        "Models/Chat.swift",
        "Models/Common.swift",
        "Models/Engine.swift",
        "Models/HomeDecor.swift",
        "Models/Inpaint.swift",
        "Models/LiveScore.swift",
        "Models/Music.swift",
        "Models/Notification.swift",
        "Models/PendingTask.swift",
        "Models/Smartcar.swift",
        "Models/Survey.swift",
        "Models/TTS.swift",
        "Models/Vision.swift",
        "Models/Visual.swift",
    ],
    module_name = "WasmClient",
    visibility = ["//visibility:public"],
    deps = [
        "@swiftpkg_swift_dependencies//:Dependencies",
        "@swiftpkg_swift_dependencies//:DependenciesMacros",
    ],
)
