import Foundation

// MARK: - Provider Enumeration

extension WasmClient {
    /// Every provider currently registered for `searchPhotos`, in the order
    /// the engine returned them. Returns `[]` while the engine is still
    /// starting up or when no provider is configured.
    ///
    /// Use this to build a provider picker UI (each `ActionInfo` has a
    /// `provider` ID for `searchPhotos(query:provider:…)` and a human-readable
    /// `providerName`). Mirrors `flow-kit-example`'s `searchPhotoProviders()`.
    public func searchPhotoProviders() async throws -> [ActionInfo] {
        try await availableActions()
            .filter { $0.actionID == ActionID.searchPhotos.rawValue }
    }

    /// Every provider currently registered for `photoVisualSearch`.
    public func photoVisualSearchProviders() async throws -> [ActionInfo] {
        try await availableActions()
            .filter { $0.actionID == ActionID.photoVisualSearch.rawValue }
    }

    /// Every provider currently registered for `listMedia` (editorial /
    /// curated feed).
    public func listMediaProviders() async throws -> [ActionInfo] {
        try await availableActions()
            .filter { $0.actionID == ActionID.listMedia.rawValue }
    }
}

// MARK: - First-Provider Conveniences
//
// The `@DependencyEndpoint` macro on `Interface.swift` already generates a
// labelled method `searchPhotos(query:provider:page:perPage:)` for the
// underlying closure, so we can't add another overload with that exact
// signature. The overloads below drop the `provider:` parameter — they always
// route to the first-available provider (empty string is the WasmClient
// convention for "auto-pick"). This matches `flow-kit-example`'s
// `searchPhotos(query:page:perPage:)` signature one-to-one and lets callers
// who don't care about provider pinning omit it entirely + rely on the
// `page = 1` / `perPage = 20` defaults.

extension WasmClient {
    /// Search photos against the first available provider, with the same
    /// defaults `flow-kit-example` uses (`page = 1`, `perPage = 20`).
    ///
    /// Pin a specific provider with the labelled
    /// `searchPhotos(query:provider:page:perPage:)` form (auto-generated by
    /// `@DependencyEndpoint`) — pass an `ActionInfo.provider` value from
    /// `searchPhotoProviders()`.
    ///
    /// Empty `query` is allowed but most providers return no results for it;
    /// for editorial / trending photos use `listMedia()` instead.
    public func searchPhotos(
        query: String,
        page: Int = 1,
        perPage: Int = 20
    ) async throws -> PhotoSearchResult {
        try await searchPhotos(query, "", page, perPage)
    }

    /// Visual search against the first available provider, with `page = 1`
    /// and `perPage = 20` defaults. Pin a provider with the labelled
    /// `photoVisualSearch(imageURL:provider:page:perPage:)` form.
    public func photoVisualSearch(
        imageURL: String,
        page: Int = 1,
        perPage: Int = 20
    ) async throws -> PhotoSearchResult {
        try await photoVisualSearch(imageURL, "", page, perPage)
    }

    /// Editorial / curated media listing against the first available
    /// provider. Pass an empty `query` (the default) to get the provider's
    /// default editorial feed — flow-kit-example uses this exact call as the
    /// empty-search fallback in `MediaView`. Pin a provider with the
    /// labelled `listMedia(query:provider:page:perPage:)` form.
    public func listMedia(
        query: String = "",
        page: Int = 1,
        perPage: Int = 20
    ) async throws -> PhotoSearchResult {
        try await listMedia(query, "", page, perPage)
    }
}
