load("@build_bazel_rules_swift//swift:swift_library.bzl", "swift_library")

swift_library(
    name = "WasmClientLive",
    srcs = [
        "Live.swift",
        "Protos/aiart.pb.swift",
        "Protos/blobstore.pb.swift",
        "Protos/homedecor.pb.swift",
        "Protos/inpaint.pb.swift",
        "Protos/livescore.pb.swift",
        "Protos/music.pb.swift",
        "Protos/openai.pb.swift",
        "Protos/smartcar.pb.swift",
        "Protos/vision.pb.swift",
        "Protos/visual.pb.swift",
        "Sessions/AIArt.swift",
        "Sessions/Blobstore.swift",
        "Sessions/Chat.swift",
        "Sessions/ChatStream.swift",
        "Sessions/HomeDecor.swift",
        "Sessions/Inpaint.swift",
        "Sessions/LiveScore.swift",
        "Sessions/Music.swift",
        "Sessions/Notification.swift",
        "Sessions/PendingTasks.swift",
        "Sessions/Smartcar.swift",
        "Sessions/Suggest.swift",
        "Sessions/Survey.swift",
        "Sessions/TTS.swift",
        "Sessions/Vision.swift",
        "Sessions/Visual.swift",
        "Sessions/Wasm.swift",
    ],
    module_name = "WasmClientLive",
    visibility = ["//visibility:public"],
    deps = [
        "//Sources/WasmClient",
        "@swiftpkg_flow_kit//:FlowKit",
        "@swiftpkg_swift_dependencies//:Dependencies",
        "@swiftpkg_swift_protobuf//:SwiftProtobuf",
    ],
)
