load("@build_bazel_rules_swift//swift:swift_library.bzl", "swift_library")

swift_library(
    name = "WasmClientLive",
    srcs = [
        "Actor.swift",
        "Live.swift",
        "Protos/aiart.pb.swift",
        "Protos/blobstore.pb.swift",
        "Protos/homedecor.pb.swift",
        "Protos/inpaint.pb.swift",
        "Protos/livescore.pb.swift",
        "Protos/music.pb.swift",
        "Protos/openai.pb.swift",
        "Protos/vision.pb.swift",
        "Protos/visual.pb.swift",
        "Sessions/AiartSession.swift",
        "Sessions/BlobstoreSession.swift",
        "Sessions/ChatSession.swift",
        "Sessions/HomedecorSession.swift",
        "Sessions/InpaintSession.swift",
        "Sessions/LivescoreSession.swift",
        "Sessions/MusicSession.swift",
        "Sessions/NotificationSession.swift",
        "Sessions/PendingTasksSession.swift",
        "Sessions/ScanSession.swift",
        "Sessions/SuggestSession.swift",
        "Sessions/SurveySession.swift",
        "Sessions/TTSSession.swift",
        "Sessions/VisualSession.swift",
    ],
    module_name = "WasmClientLive",
    visibility = ["//visibility:public"],
    deps = [
        "//Sources/WasmClient",
        "@swiftpkg_flow_kit//:FlowKit",
        "@swiftpkg_swift_dependencies//:Dependencies",
        "@swiftpkg_swift_protobuf//:SwiftProtobuf",
    ],
)
